/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! A runtime RMS gRPC mock.
//!
//! The RMS API is served by an external service that drives real rack
//! hardware. Simulated hardware has no such service, so rack workflows that
//! call RMS cannot run against a simulated fleet. This crate implements the
//! RMS gRPC surface directly, using the server bindings generated by
//! `librms`, so a normally configured NICo process can talk to it over the
//! wire without knowing it is not the real thing.
//!
//! The mock is deliberately independent of machine-a-tron: it owns
//! protocol behaviour only, and reads hardware state through a trait its host
//! implements. That boundary is what lets a future multi-pod gateway supply a
//! fan-out inventory instead of a local one.

mod config;
mod envelope;
mod fabric;
mod firmware;
mod inventory;
mod jobs;
mod lifecycle;
mod nvos;
mod resolve;
mod router;
mod service_v1;
mod service_v2;

pub use config::{FaultConfig, RmsMockConfig};
pub use inventory::{RmsInventory, SimNode, SimNodeKind, SimPowerState};
/// The V1 protobuf module. Aliased because both service impls refer to it
/// constantly, and because `rack_manager_v2` defines same-named messages that
/// must not be confused with these.
pub(crate) use librms::protos::rack_manager as rms;
/// The power operation an RMS request names, handed to the host as is.
pub use librms::protos::rack_manager::PowerOperation;
/// The V2 protobuf module.
pub(crate) use librms::protos::rack_manager_v2 as rms_v2;
pub use router::router;

/// Lock a mutex, recovering it if a panicking holder poisoned it.
pub(crate) fn lock<T>(m: &std::sync::Mutex<T>) -> std::sync::MutexGuard<'_, T> {
    m.lock().unwrap_or_else(|e| e.into_inner())
}

/// A simulated RMS instance.
///
/// One mock serves both `RackManager` and `RackManagerV2`; the two are
/// separate gRPC services with separate wire paths, so both must be mounted.
pub struct RmsMock {
    inventory: std::sync::Arc<dyn RmsInventory>,
    jobs: jobs::JobStore,
    fabric: fabric::FabricState,
    config: RmsMockConfig,
}

impl RmsMock {
    pub fn new(inventory: std::sync::Arc<dyn RmsInventory>, config: RmsMockConfig) -> Self {
        Self {
            inventory,
            jobs: jobs::JobStore::new(config.faults.clone()),
            fabric: fabric::FabricState::new(),
            config,
        }
    }

    /// Poll a job and apply what its completion does to the mock.
    pub(crate) fn observe_job(&self, job_id: &jobs::JobId) -> jobs::JobStatus {
        let status = self.jobs.observe(job_id);
        for job in std::iter::once(&status).chain(&status.children) {
            // Only a node's job carries an effect, and it names its node.
            let (Some(effect), Some(rack_id), Some(node_id)) =
                (job.effect, &job.rack_id, &job.node_id)
            else {
                continue;
            };
            match effect {
                jobs::Effect::ResetFabricRole => self.fabric.reset(rack_id, node_id),
            }
        }
        status
    }
}

/// An [`RmsInventory`] whose node set is fixed at construction.
///
/// Every `nodes()` call returns the same shared snapshot; nothing is rebuilt
/// or observed after construction. Power is the one thing that moves: every
/// device starts on, an operation the simulated BMC would refuse is refused
/// here too, and a restart has completed by the time it is read because
/// nothing here keeps time. Tests and hosts with nothing to report use this in
/// place of a live inventory.
pub struct StaticInventory {
    nodes: std::sync::Arc<[SimNode]>,
    power: std::sync::Mutex<std::collections::HashMap<mac_address::MacAddress, SimPowerState>>,
}

impl StaticInventory {
    /// Wraps a fixed set of nodes; the snapshot is shared, never rebuilt.
    pub fn new(nodes: std::sync::Arc<[SimNode]>) -> Self {
        Self {
            nodes,
            power: std::sync::Mutex::default(),
        }
    }

    fn has_bmc(&self, bmc_mac: mac_address::MacAddress) -> eyre::Result<()> {
        eyre::ensure!(
            self.nodes.iter().any(|n| n.bmc_mac == Some(bmc_mac)),
            "no simulated device has BMC MAC {bmc_mac}"
        );
        Ok(())
    }
}

impl RmsInventory for StaticInventory {
    fn nodes(&self) -> std::sync::Arc<[SimNode]> {
        std::sync::Arc::clone(&self.nodes)
    }

    fn power_state(&self, bmc_mac: mac_address::MacAddress) -> eyre::Result<SimPowerState> {
        self.has_bmc(bmc_mac)?;
        Ok(lock(&self.power)
            .get(&bmc_mac)
            .copied()
            .unwrap_or(SimPowerState::On))
    }

    fn set_power(&self, bmc_mac: mac_address::MacAddress, op: PowerOperation) -> eyre::Result<()> {
        let power = match (op, self.power_state(bmc_mac)?) {
            (PowerOperation::Unspecified, _) => eyre::bail!("power operation is unspecified"),
            (PowerOperation::On | PowerOperation::ForceOn, SimPowerState::On) => {
                eyre::bail!("cannot power on machine, it is already on")
            }
            (
                PowerOperation::Off
                | PowerOperation::ForceOff
                | PowerOperation::GracefulShutdown
                | PowerOperation::GracefulRestart
                | PowerOperation::ForceRestart,
                SimPowerState::Off,
            ) => eyre::bail!("cannot power off machine, it is already off"),
            (PowerOperation::On | PowerOperation::ForceOn, SimPowerState::Off) => SimPowerState::On,
            (
                PowerOperation::Off | PowerOperation::ForceOff | PowerOperation::GracefulShutdown,
                SimPowerState::On,
            ) => SimPowerState::Off,
            // Nothing here keeps time, so a restart has completed by the time
            // it is read; a power cycle is the one restart allowed from off.
            (
                PowerOperation::Reset
                | PowerOperation::GracefulRestart
                | PowerOperation::ForceRestart,
                _,
            ) => SimPowerState::On,
        };
        lock(&self.power).insert(bmc_mac, power);
        Ok(())
    }
}
