{{- $nicoApi := index .Values "nico-api" | default dict -}}
{{- $credentials := index $nicoApi "credentials" | default dict -}}
{{- $file := index $credentials "file" | default dict -}}
{{- $existingSecret := index $file "existingSecret" | default dict -}}
{{- $name := index $existingSecret "name" | default "" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-values-inspector
data:
  result.json: |-
    {"credentialFileSecretName": {{ printf "%v" $name | toJson }}}
