{{- $ipv6 := default (dict) .Values.ipv6 -}}
apiVersion: v1
kind: Service
metadata:
  name: nico-unbound
  namespace: {{ include "unbound.namespace" . }}
  labels:
    {{- include "unbound.labels" . | nindent 4 }}
    {{- if .Values.exporter.enabled }}
    app.kubernetes.io/metrics: nico-unbound
    {{- end }}
  annotations:
    {{- include "unbound.annotations" . | nindent 4 }}
spec:
  ipFamilyPolicy: {{ if $ipv6.enabled }}PreferDualStack{{ else }}SingleStack{{ end }}
  ipFamilies: [IPv4]
  selector:
    {{- include "unbound.selectorLabels" . | nindent 4 }}
  ports:
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    {{- if .Values.exporter.enabled }}
    - port: 9167
      targetPort: metrics
      protocol: TCP
      name: unbound-metrics
    {{- end }}
