/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! A runtime NMX-C gRPC mock.
//!
//! NMX-C is the NVLink controller that runs on a rack's NVLink switches and
//! owns that rack's GPU partitions. Simulated racks have no such controller,
//! so the NVLink workflows that call it cannot run against a simulated fleet.
//! This crate implements the `NMX_Controller` gRPC surface directly, using the
//! server bindings generated by `libnmxc`, so a normally configured NICo
//! process can talk to it over the wire without knowing it is not the real
//! thing.
//!
//! One mock stands in for every rack's controller at once. A real deployment
//! has one NMX-C per rack, reached at that rack's switch NVOS address; here
//! every such address lands on the same listener, so the mock picks the rack
//! from the authority the client addressed (see [`authority`]) and keeps an
//! independent partition table per rack.
//!
//! The mock is deliberately independent of machine-a-tron: it owns protocol
//! behaviour and partition state only, and reads the simulated racks through
//! a trait its host implements.

mod authority;
mod config;
mod inventory;
mod router;
mod service;
mod state;

use std::collections::HashMap;
use std::sync::{Arc, Mutex, PoisonError};

pub use config::NmxcMockConfig;
pub use inventory::{NmxcInventory, SimComputeNode, SimDomain, SimGpu, SimSwitch, StaticInventory};
/// The generated protobuf module, aliased because the service impl refers to
/// it constantly.
pub(crate) use libnmxc::nmxc_model as nmx;
pub use router::router;

use crate::state::DomainState;

/// A simulated NMX-C, answering for every domain its inventory reports.
pub struct NmxcMock {
    inventory: Arc<dyn NmxcInventory>,
    config: NmxcMockConfig,
    /// Partition tables by domain key. Entries are created on first contact
    /// and never dropped: a rack that disappears from a snapshot and returns
    /// finds its partitions where it left them, as it would on real hardware.
    domains: Mutex<HashMap<String, DomainState>>,
}

impl NmxcMock {
    pub fn new(inventory: Arc<dyn NmxcInventory>, config: NmxcMockConfig) -> Self {
        Self {
            inventory,
            config,
            domains: Mutex::new(HashMap::new()),
        }
    }

    /// Run `f` against the domain a request addressed and that domain's
    /// partition table.
    ///
    /// The table lock is held only for the duration of `f`, which is
    /// synchronous, so no request ever awaits while holding it.
    fn with_domain<T, R>(
        &self,
        request: &tonic::Request<T>,
        f: impl FnOnce(&SimDomain, &mut DomainState) -> R,
    ) -> Result<R, tonic::Status> {
        let domains = self.inventory.domains();
        let addressed = request
            .extensions()
            .get::<authority::RequestAuthority>()
            .map(|authority| authority.0.as_str());
        let domain = authority::resolve_domain(addressed, &domains)?;
        let mut tables = self.domains.lock().unwrap_or_else(PoisonError::into_inner);
        let table = tables
            .entry(domain.key.clone())
            .or_insert_with(|| self.new_domain_state(domain));
        Ok(f(domain, table))
    }

    fn new_domain_state(&self, domain: &SimDomain) -> DomainState {
        let default_partition = self.config.boot_with_default_partition.then_some((
            self.config.default_partition_id,
            self.config.default_partition_name.as_str(),
        ));
        DomainState::new(domain.gpu_uids(), default_partition)
    }
}
