# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nico-site-health-probe.name" . }}
  namespace: {{ include "nico-site-health-probe.namespace" . }}
  labels:
    {{- include "nico-site-health-probe.labels" . | nindent 4 }}
automountServiceAccountToken: false
