// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the DpuExtensionServiceDpfHelmChartRollingUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DpuExtensionServiceDpfHelmChartRollingUpdate{}

// DpuExtensionServiceDpfHelmChartRollingUpdate Optional rolling-update limits passed to DPF
type DpuExtensionServiceDpfHelmChartRollingUpdate struct {
	// Optional additional pod count or percentage string, for example 1 or \"25%\"
	MaxSurge NullableDpuExtensionServiceDpfHelmChartIntOrString `json:"maxSurge,omitempty"`
	// Optional unavailable pod count or percentage string, for example 1 or \"25%\"
	MaxUnavailable NullableDpuExtensionServiceDpfHelmChartIntOrString `json:"maxUnavailable,omitempty"`
}

// NewDpuExtensionServiceDpfHelmChartRollingUpdate instantiates a new DpuExtensionServiceDpfHelmChartRollingUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDpuExtensionServiceDpfHelmChartRollingUpdate() *DpuExtensionServiceDpfHelmChartRollingUpdate {
	this := DpuExtensionServiceDpfHelmChartRollingUpdate{}
	return &this
}

// NewDpuExtensionServiceDpfHelmChartRollingUpdateWithDefaults instantiates a new DpuExtensionServiceDpfHelmChartRollingUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDpuExtensionServiceDpfHelmChartRollingUpdateWithDefaults() *DpuExtensionServiceDpfHelmChartRollingUpdate {
	this := DpuExtensionServiceDpfHelmChartRollingUpdate{}
	return &this
}

// GetMaxSurge returns the MaxSurge field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DpuExtensionServiceDpfHelmChartRollingUpdate) GetMaxSurge() DpuExtensionServiceDpfHelmChartIntOrString {
	if o == nil || IsNil(o.MaxSurge.Get()) {
		var ret DpuExtensionServiceDpfHelmChartIntOrString
		return ret
	}
	return *o.MaxSurge.Get()
}

// GetMaxSurgeOk returns a tuple with the MaxSurge field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuExtensionServiceDpfHelmChartRollingUpdate) GetMaxSurgeOk() (*DpuExtensionServiceDpfHelmChartIntOrString, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxSurge.Get(), o.MaxSurge.IsSet()
}

// HasMaxSurge returns a boolean if a field has been set.
func (o *DpuExtensionServiceDpfHelmChartRollingUpdate) HasMaxSurge() bool {
	if o != nil && o.MaxSurge.IsSet() {
		return true
	}

	return false
}

// SetMaxSurge gets a reference to the given NullableDpuExtensionServiceDpfHelmChartIntOrString and assigns it to the MaxSurge field.
func (o *DpuExtensionServiceDpfHelmChartRollingUpdate) SetMaxSurge(v DpuExtensionServiceDpfHelmChartIntOrString) {
	o.MaxSurge.Set(&v)
}

// SetMaxSurgeNil sets the value for MaxSurge to be an explicit nil
func (o *DpuExtensionServiceDpfHelmChartRollingUpdate) SetMaxSurgeNil() {
	o.MaxSurge.Set(nil)
}

// UnsetMaxSurge ensures that no value is present for MaxSurge, not even an explicit nil
func (o *DpuExtensionServiceDpfHelmChartRollingUpdate) UnsetMaxSurge() {
	o.MaxSurge.Unset()
}

// GetMaxUnavailable returns the MaxUnavailable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DpuExtensionServiceDpfHelmChartRollingUpdate) GetMaxUnavailable() DpuExtensionServiceDpfHelmChartIntOrString {
	if o == nil || IsNil(o.MaxUnavailable.Get()) {
		var ret DpuExtensionServiceDpfHelmChartIntOrString
		return ret
	}
	return *o.MaxUnavailable.Get()
}

// GetMaxUnavailableOk returns a tuple with the MaxUnavailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuExtensionServiceDpfHelmChartRollingUpdate) GetMaxUnavailableOk() (*DpuExtensionServiceDpfHelmChartIntOrString, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxUnavailable.Get(), o.MaxUnavailable.IsSet()
}

// HasMaxUnavailable returns a boolean if a field has been set.
func (o *DpuExtensionServiceDpfHelmChartRollingUpdate) HasMaxUnavailable() bool {
	if o != nil && o.MaxUnavailable.IsSet() {
		return true
	}

	return false
}

// SetMaxUnavailable gets a reference to the given NullableDpuExtensionServiceDpfHelmChartIntOrString and assigns it to the MaxUnavailable field.
func (o *DpuExtensionServiceDpfHelmChartRollingUpdate) SetMaxUnavailable(v DpuExtensionServiceDpfHelmChartIntOrString) {
	o.MaxUnavailable.Set(&v)
}

// SetMaxUnavailableNil sets the value for MaxUnavailable to be an explicit nil
func (o *DpuExtensionServiceDpfHelmChartRollingUpdate) SetMaxUnavailableNil() {
	o.MaxUnavailable.Set(nil)
}

// UnsetMaxUnavailable ensures that no value is present for MaxUnavailable, not even an explicit nil
func (o *DpuExtensionServiceDpfHelmChartRollingUpdate) UnsetMaxUnavailable() {
	o.MaxUnavailable.Unset()
}

func (o DpuExtensionServiceDpfHelmChartRollingUpdate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DpuExtensionServiceDpfHelmChartRollingUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.MaxSurge.IsSet() {
		toSerialize["maxSurge"] = o.MaxSurge.Get()
	}
	if o.MaxUnavailable.IsSet() {
		toSerialize["maxUnavailable"] = o.MaxUnavailable.Get()
	}
	return toSerialize, nil
}

type NullableDpuExtensionServiceDpfHelmChartRollingUpdate struct {
	value *DpuExtensionServiceDpfHelmChartRollingUpdate
	isSet bool
}

func (v NullableDpuExtensionServiceDpfHelmChartRollingUpdate) Get() *DpuExtensionServiceDpfHelmChartRollingUpdate {
	return v.value
}

func (v *NullableDpuExtensionServiceDpfHelmChartRollingUpdate) Set(val *DpuExtensionServiceDpfHelmChartRollingUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceDpfHelmChartRollingUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceDpfHelmChartRollingUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceDpfHelmChartRollingUpdate(val *DpuExtensionServiceDpfHelmChartRollingUpdate) *NullableDpuExtensionServiceDpfHelmChartRollingUpdate {
	return &NullableDpuExtensionServiceDpfHelmChartRollingUpdate{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceDpfHelmChartRollingUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceDpfHelmChartRollingUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
