// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SpectrumXAttachment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpectrumXAttachment{}

// SpectrumXAttachment A SpectrumX Attachment binds one SpectrumX Partition to one device instance on an Instance. macAddress and ipAddress are allocated by the Site and reported through inventory, so they are absent until the attachment reaches Ready
type SpectrumXAttachment struct {
	// Unique UUID v4 identifier for the SpectrumX Attachment
	Id string `json:"id"`
	// ID of the associated Instance
	InstanceId string `json:"instanceId"`
	// ID of the associated SpectrumX Partition
	SpectrumXPartitionId string `json:"spectrumXPartitionId"`
	// Summary of the SpectrumX Partition
	SpectrumXPartition *SpectrumXPartitionSummary `json:"spectrumXPartition,omitempty"`
	// SpectrumX device the Partition is attached over, matching the device description reported for the Machine's SpectrumX interfaces
	Device string `json:"device"`
	// Index of the device, identifying which interface card the Partition is attached to
	DeviceInstance int32 `json:"deviceInstance"`
	// Type of SpectrumX attachment. `Virtual` is not currently supported and is rejected
	AttachmentType string `json:"attachmentType"`
	// Virtual function the attachment uses. Not currently supported
	VirtualFunctionId NullableInt32 `json:"virtualFunctionId,omitempty"`
	// MAC address the Site allocated for the attachment
	MacAddress NullableString `json:"macAddress,omitempty"`
	// IP address the Site allocated for the attachment
	IpAddress NullableString `json:"ipAddress,omitempty"`
	// Status of the SpectrumX Attachment
	Status string `json:"status"`
	// ISO datetime string for when the SpectrumX Attachment was created
	Created *time.Time `json:"created,omitempty"`
	// ISO datetime string for when the SpectrumX Attachment was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

type _SpectrumXAttachment SpectrumXAttachment

// NewSpectrumXAttachment instantiates a new SpectrumXAttachment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpectrumXAttachment(id string, instanceId string, spectrumXPartitionId string, device string, deviceInstance int32, attachmentType string, status string) *SpectrumXAttachment {
	this := SpectrumXAttachment{}
	this.Id = id
	this.InstanceId = instanceId
	this.SpectrumXPartitionId = spectrumXPartitionId
	this.Device = device
	this.DeviceInstance = deviceInstance
	this.AttachmentType = attachmentType
	this.Status = status
	return &this
}

// NewSpectrumXAttachmentWithDefaults instantiates a new SpectrumXAttachment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpectrumXAttachmentWithDefaults() *SpectrumXAttachment {
	this := SpectrumXAttachment{}
	return &this
}

// GetId returns the Id field value
func (o *SpectrumXAttachment) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SpectrumXAttachment) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SpectrumXAttachment) SetId(v string) {
	o.Id = v
}

// GetInstanceId returns the InstanceId field value
func (o *SpectrumXAttachment) GetInstanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value
// and a boolean to check if the value has been set.
func (o *SpectrumXAttachment) GetInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceId, true
}

// SetInstanceId sets field value
func (o *SpectrumXAttachment) SetInstanceId(v string) {
	o.InstanceId = v
}

// GetSpectrumXPartitionId returns the SpectrumXPartitionId field value
func (o *SpectrumXAttachment) GetSpectrumXPartitionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpectrumXPartitionId
}

// GetSpectrumXPartitionIdOk returns a tuple with the SpectrumXPartitionId field value
// and a boolean to check if the value has been set.
func (o *SpectrumXAttachment) GetSpectrumXPartitionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpectrumXPartitionId, true
}

// SetSpectrumXPartitionId sets field value
func (o *SpectrumXAttachment) SetSpectrumXPartitionId(v string) {
	o.SpectrumXPartitionId = v
}

// GetSpectrumXPartition returns the SpectrumXPartition field value if set, zero value otherwise.
func (o *SpectrumXAttachment) GetSpectrumXPartition() SpectrumXPartitionSummary {
	if o == nil || IsNil(o.SpectrumXPartition) {
		var ret SpectrumXPartitionSummary
		return ret
	}
	return *o.SpectrumXPartition
}

// GetSpectrumXPartitionOk returns a tuple with the SpectrumXPartition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpectrumXAttachment) GetSpectrumXPartitionOk() (*SpectrumXPartitionSummary, bool) {
	if o == nil || IsNil(o.SpectrumXPartition) {
		return nil, false
	}
	return o.SpectrumXPartition, true
}

// HasSpectrumXPartition returns a boolean if a field has been set.
func (o *SpectrumXAttachment) HasSpectrumXPartition() bool {
	if o != nil && !IsNil(o.SpectrumXPartition) {
		return true
	}

	return false
}

// SetSpectrumXPartition gets a reference to the given SpectrumXPartitionSummary and assigns it to the SpectrumXPartition field.
func (o *SpectrumXAttachment) SetSpectrumXPartition(v SpectrumXPartitionSummary) {
	o.SpectrumXPartition = &v
}

// GetDevice returns the Device field value
func (o *SpectrumXAttachment) GetDevice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *SpectrumXAttachment) GetDeviceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *SpectrumXAttachment) SetDevice(v string) {
	o.Device = v
}

// GetDeviceInstance returns the DeviceInstance field value
func (o *SpectrumXAttachment) GetDeviceInstance() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DeviceInstance
}

// GetDeviceInstanceOk returns a tuple with the DeviceInstance field value
// and a boolean to check if the value has been set.
func (o *SpectrumXAttachment) GetDeviceInstanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceInstance, true
}

// SetDeviceInstance sets field value
func (o *SpectrumXAttachment) SetDeviceInstance(v int32) {
	o.DeviceInstance = v
}

// GetAttachmentType returns the AttachmentType field value
func (o *SpectrumXAttachment) GetAttachmentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttachmentType
}

// GetAttachmentTypeOk returns a tuple with the AttachmentType field value
// and a boolean to check if the value has been set.
func (o *SpectrumXAttachment) GetAttachmentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttachmentType, true
}

// SetAttachmentType sets field value
func (o *SpectrumXAttachment) SetAttachmentType(v string) {
	o.AttachmentType = v
}

// GetVirtualFunctionId returns the VirtualFunctionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpectrumXAttachment) GetVirtualFunctionId() int32 {
	if o == nil || IsNil(o.VirtualFunctionId.Get()) {
		var ret int32
		return ret
	}
	return *o.VirtualFunctionId.Get()
}

// GetVirtualFunctionIdOk returns a tuple with the VirtualFunctionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpectrumXAttachment) GetVirtualFunctionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VirtualFunctionId.Get(), o.VirtualFunctionId.IsSet()
}

// HasVirtualFunctionId returns a boolean if a field has been set.
func (o *SpectrumXAttachment) HasVirtualFunctionId() bool {
	if o != nil && o.VirtualFunctionId.IsSet() {
		return true
	}

	return false
}

// SetVirtualFunctionId gets a reference to the given NullableInt32 and assigns it to the VirtualFunctionId field.
func (o *SpectrumXAttachment) SetVirtualFunctionId(v int32) {
	o.VirtualFunctionId.Set(&v)
}

// SetVirtualFunctionIdNil sets the value for VirtualFunctionId to be an explicit nil
func (o *SpectrumXAttachment) SetVirtualFunctionIdNil() {
	o.VirtualFunctionId.Set(nil)
}

// UnsetVirtualFunctionId ensures that no value is present for VirtualFunctionId, not even an explicit nil
func (o *SpectrumXAttachment) UnsetVirtualFunctionId() {
	o.VirtualFunctionId.Unset()
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpectrumXAttachment) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress.Get()) {
		var ret string
		return ret
	}
	return *o.MacAddress.Get()
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpectrumXAttachment) GetMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MacAddress.Get(), o.MacAddress.IsSet()
}

// HasMacAddress returns a boolean if a field has been set.
func (o *SpectrumXAttachment) HasMacAddress() bool {
	if o != nil && o.MacAddress.IsSet() {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given NullableString and assigns it to the MacAddress field.
func (o *SpectrumXAttachment) SetMacAddress(v string) {
	o.MacAddress.Set(&v)
}

// SetMacAddressNil sets the value for MacAddress to be an explicit nil
func (o *SpectrumXAttachment) SetMacAddressNil() {
	o.MacAddress.Set(nil)
}

// UnsetMacAddress ensures that no value is present for MacAddress, not even an explicit nil
func (o *SpectrumXAttachment) UnsetMacAddress() {
	o.MacAddress.Unset()
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpectrumXAttachment) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress.Get()) {
		var ret string
		return ret
	}
	return *o.IpAddress.Get()
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpectrumXAttachment) GetIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpAddress.Get(), o.IpAddress.IsSet()
}

// HasIpAddress returns a boolean if a field has been set.
func (o *SpectrumXAttachment) HasIpAddress() bool {
	if o != nil && o.IpAddress.IsSet() {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given NullableString and assigns it to the IpAddress field.
func (o *SpectrumXAttachment) SetIpAddress(v string) {
	o.IpAddress.Set(&v)
}

// SetIpAddressNil sets the value for IpAddress to be an explicit nil
func (o *SpectrumXAttachment) SetIpAddressNil() {
	o.IpAddress.Set(nil)
}

// UnsetIpAddress ensures that no value is present for IpAddress, not even an explicit nil
func (o *SpectrumXAttachment) UnsetIpAddress() {
	o.IpAddress.Unset()
}

// GetStatus returns the Status field value
func (o *SpectrumXAttachment) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SpectrumXAttachment) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SpectrumXAttachment) SetStatus(v string) {
	o.Status = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *SpectrumXAttachment) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpectrumXAttachment) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *SpectrumXAttachment) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *SpectrumXAttachment) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *SpectrumXAttachment) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpectrumXAttachment) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *SpectrumXAttachment) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *SpectrumXAttachment) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o SpectrumXAttachment) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpectrumXAttachment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["instanceId"] = o.InstanceId
	toSerialize["spectrumXPartitionId"] = o.SpectrumXPartitionId
	if !IsNil(o.SpectrumXPartition) {
		toSerialize["spectrumXPartition"] = o.SpectrumXPartition
	}
	toSerialize["device"] = o.Device
	toSerialize["deviceInstance"] = o.DeviceInstance
	toSerialize["attachmentType"] = o.AttachmentType
	if o.VirtualFunctionId.IsSet() {
		toSerialize["virtualFunctionId"] = o.VirtualFunctionId.Get()
	}
	if o.MacAddress.IsSet() {
		toSerialize["macAddress"] = o.MacAddress.Get()
	}
	if o.IpAddress.IsSet() {
		toSerialize["ipAddress"] = o.IpAddress.Get()
	}
	toSerialize["status"] = o.Status
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

func (o *SpectrumXAttachment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"instanceId",
		"spectrumXPartitionId",
		"device",
		"deviceInstance",
		"attachmentType",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpectrumXAttachment := _SpectrumXAttachment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSpectrumXAttachment)

	if err != nil {
		return err
	}

	*o = SpectrumXAttachment(varSpectrumXAttachment)

	return err
}

type NullableSpectrumXAttachment struct {
	value *SpectrumXAttachment
	isSet bool
}

func (v NullableSpectrumXAttachment) Get() *SpectrumXAttachment {
	return v.value
}

func (v *NullableSpectrumXAttachment) Set(val *SpectrumXAttachment) {
	v.value = val
	v.isSet = true
}

func (v NullableSpectrumXAttachment) IsSet() bool {
	return v.isSet
}

func (v *NullableSpectrumXAttachment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpectrumXAttachment(val *SpectrumXAttachment) *NullableSpectrumXAttachment {
	return &NullableSpectrumXAttachment{value: val, isSet: true}
}

func (v NullableSpectrumXAttachment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpectrumXAttachment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
