// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// checks if the DpuExtensionServiceDpfHelmChartData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DpuExtensionServiceDpfHelmChartData{}

// DpuExtensionServiceDpfHelmChartData DpfHelmChart configuration documented as an object; requests serialize this object into the `data` string.
type DpuExtensionServiceDpfHelmChartData struct {
	// Helm repository URL beginning with https:// or oci://
	RepoURL string `json:"repoURL" validate:"regexp=^(https://|oci://)"`
	// Helm chart name
	ChartName string `json:"chartName"`
	// Helm chart version
	ChartVersion string `json:"chartVersion"`
	// DPF privileged-workload setting. This is a literal dotted key, not a nested security object; false is valid.
	SecurityPrivileged bool `json:"security.privileged"`
	// Optional chart values. values.serviceDaemonSet.nodeSelector is reserved for NICo and must not be supplied.
	Values               map[string]interface{}                                  `json:"values,omitempty"`
	ServiceDaemonSet     NullableDpuExtensionServiceDpfHelmChartServiceDaemonSet `json:"serviceDaemonSet,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DpuExtensionServiceDpfHelmChartData DpuExtensionServiceDpfHelmChartData

// NewDpuExtensionServiceDpfHelmChartData instantiates a new DpuExtensionServiceDpfHelmChartData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDpuExtensionServiceDpfHelmChartData(repoURL string, chartName string, chartVersion string, securityPrivileged bool) *DpuExtensionServiceDpfHelmChartData {
	this := DpuExtensionServiceDpfHelmChartData{}
	this.RepoURL = repoURL
	this.ChartName = chartName
	this.ChartVersion = chartVersion
	this.SecurityPrivileged = securityPrivileged
	return &this
}

// NewDpuExtensionServiceDpfHelmChartDataWithDefaults instantiates a new DpuExtensionServiceDpfHelmChartData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDpuExtensionServiceDpfHelmChartDataWithDefaults() *DpuExtensionServiceDpfHelmChartData {
	this := DpuExtensionServiceDpfHelmChartData{}
	return &this
}

// GetRepoURL returns the RepoURL field value
func (o *DpuExtensionServiceDpfHelmChartData) GetRepoURL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RepoURL
}

// GetRepoURLOk returns a tuple with the RepoURL field value
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceDpfHelmChartData) GetRepoURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepoURL, true
}

// SetRepoURL sets field value
func (o *DpuExtensionServiceDpfHelmChartData) SetRepoURL(v string) {
	o.RepoURL = v
}

// GetChartName returns the ChartName field value
func (o *DpuExtensionServiceDpfHelmChartData) GetChartName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChartName
}

// GetChartNameOk returns a tuple with the ChartName field value
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceDpfHelmChartData) GetChartNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChartName, true
}

// SetChartName sets field value
func (o *DpuExtensionServiceDpfHelmChartData) SetChartName(v string) {
	o.ChartName = v
}

// GetChartVersion returns the ChartVersion field value
func (o *DpuExtensionServiceDpfHelmChartData) GetChartVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChartVersion
}

// GetChartVersionOk returns a tuple with the ChartVersion field value
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceDpfHelmChartData) GetChartVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChartVersion, true
}

// SetChartVersion sets field value
func (o *DpuExtensionServiceDpfHelmChartData) SetChartVersion(v string) {
	o.ChartVersion = v
}

// GetSecurityPrivileged returns the SecurityPrivileged field value
func (o *DpuExtensionServiceDpfHelmChartData) GetSecurityPrivileged() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SecurityPrivileged
}

// GetSecurityPrivilegedOk returns a tuple with the SecurityPrivileged field value
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceDpfHelmChartData) GetSecurityPrivilegedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecurityPrivileged, true
}

// SetSecurityPrivileged sets field value
func (o *DpuExtensionServiceDpfHelmChartData) SetSecurityPrivileged(v bool) {
	o.SecurityPrivileged = v
}

// GetValues returns the Values field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DpuExtensionServiceDpfHelmChartData) GetValues() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuExtensionServiceDpfHelmChartData) GetValuesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Values) {
		return map[string]interface{}{}, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *DpuExtensionServiceDpfHelmChartData) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]interface{} and assigns it to the Values field.
func (o *DpuExtensionServiceDpfHelmChartData) SetValues(v map[string]interface{}) {
	o.Values = v
}

// GetServiceDaemonSet returns the ServiceDaemonSet field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DpuExtensionServiceDpfHelmChartData) GetServiceDaemonSet() DpuExtensionServiceDpfHelmChartServiceDaemonSet {
	if o == nil || IsNil(o.ServiceDaemonSet.Get()) {
		var ret DpuExtensionServiceDpfHelmChartServiceDaemonSet
		return ret
	}
	return *o.ServiceDaemonSet.Get()
}

// GetServiceDaemonSetOk returns a tuple with the ServiceDaemonSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuExtensionServiceDpfHelmChartData) GetServiceDaemonSetOk() (*DpuExtensionServiceDpfHelmChartServiceDaemonSet, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceDaemonSet.Get(), o.ServiceDaemonSet.IsSet()
}

// HasServiceDaemonSet returns a boolean if a field has been set.
func (o *DpuExtensionServiceDpfHelmChartData) HasServiceDaemonSet() bool {
	if o != nil && o.ServiceDaemonSet.IsSet() {
		return true
	}

	return false
}

// SetServiceDaemonSet gets a reference to the given NullableDpuExtensionServiceDpfHelmChartServiceDaemonSet and assigns it to the ServiceDaemonSet field.
func (o *DpuExtensionServiceDpfHelmChartData) SetServiceDaemonSet(v DpuExtensionServiceDpfHelmChartServiceDaemonSet) {
	o.ServiceDaemonSet.Set(&v)
}

// SetServiceDaemonSetNil sets the value for ServiceDaemonSet to be an explicit nil
func (o *DpuExtensionServiceDpfHelmChartData) SetServiceDaemonSetNil() {
	o.ServiceDaemonSet.Set(nil)
}

// UnsetServiceDaemonSet ensures that no value is present for ServiceDaemonSet, not even an explicit nil
func (o *DpuExtensionServiceDpfHelmChartData) UnsetServiceDaemonSet() {
	o.ServiceDaemonSet.Unset()
}

func (o DpuExtensionServiceDpfHelmChartData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DpuExtensionServiceDpfHelmChartData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["repoURL"] = o.RepoURL
	toSerialize["chartName"] = o.ChartName
	toSerialize["chartVersion"] = o.ChartVersion
	toSerialize["security.privileged"] = o.SecurityPrivileged
	if o.Values != nil {
		toSerialize["values"] = o.Values
	}
	if o.ServiceDaemonSet.IsSet() {
		toSerialize["serviceDaemonSet"] = o.ServiceDaemonSet.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DpuExtensionServiceDpfHelmChartData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"repoURL",
		"chartName",
		"chartVersion",
		"security.privileged",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDpuExtensionServiceDpfHelmChartData := _DpuExtensionServiceDpfHelmChartData{}

	err = json.Unmarshal(data, &varDpuExtensionServiceDpfHelmChartData)

	if err != nil {
		return err
	}

	*o = DpuExtensionServiceDpfHelmChartData(varDpuExtensionServiceDpfHelmChartData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "repoURL")
		delete(additionalProperties, "chartName")
		delete(additionalProperties, "chartVersion")
		delete(additionalProperties, "security.privileged")
		delete(additionalProperties, "values")
		delete(additionalProperties, "serviceDaemonSet")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDpuExtensionServiceDpfHelmChartData struct {
	value *DpuExtensionServiceDpfHelmChartData
	isSet bool
}

func (v NullableDpuExtensionServiceDpfHelmChartData) Get() *DpuExtensionServiceDpfHelmChartData {
	return v.value
}

func (v *NullableDpuExtensionServiceDpfHelmChartData) Set(val *DpuExtensionServiceDpfHelmChartData) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceDpfHelmChartData) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceDpfHelmChartData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceDpfHelmChartData(val *DpuExtensionServiceDpfHelmChartData) *NullableDpuExtensionServiceDpfHelmChartData {
	return &NullableDpuExtensionServiceDpfHelmChartData{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceDpfHelmChartData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceDpfHelmChartData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
