/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// MachineStatus Status values for Machine objects
type MachineStatus string

// List of MachineStatus
const (
	MACHINESTATUS_INITIALIZING   MachineStatus = "Initializing"
	MACHINESTATUS_READY          MachineStatus = "Ready"
	MACHINESTATUS_RESET          MachineStatus = "Reset"
	MACHINESTATUS_MAINTENANCE    MachineStatus = "Maintenance"
	MACHINESTATUS_IN_USE         MachineStatus = "InUse"
	MACHINESTATUS_ERROR          MachineStatus = "Error"
	MACHINESTATUS_DECOMMISSIONED MachineStatus = "Decommissioned"
	MACHINESTATUS_UNKNOWN        MachineStatus = "Unknown"
)

// All allowed values of MachineStatus enum
var AllowedMachineStatusEnumValues = []MachineStatus{
	"Initializing",
	"Ready",
	"Reset",
	"Maintenance",
	"InUse",
	"Error",
	"Decommissioned",
	"Unknown",
}

func (v *MachineStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MachineStatus(value)
	for _, existing := range AllowedMachineStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MachineStatus", value)
}

// NewMachineStatusFromValue returns a pointer to a valid MachineStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMachineStatusFromValue(v string) (*MachineStatus, error) {
	ev := MachineStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MachineStatus: valid values are %v", v, AllowedMachineStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MachineStatus) IsValid() bool {
	for _, existing := range AllowedMachineStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MachineStatus value
func (v MachineStatus) Ptr() *MachineStatus {
	return &v
}

type NullableMachineStatus struct {
	value *MachineStatus
	isSet bool
}

func (v NullableMachineStatus) Get() *MachineStatus {
	return v.value
}

func (v *NullableMachineStatus) Set(val *MachineStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineStatus(val *MachineStatus) *NullableMachineStatus {
	return &NullableMachineStatus{value: val, isSet: true}
}

func (v NullableMachineStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
