// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VpcRoutingState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcRoutingState{}

// VpcRoutingState Authoritative persisted routing state read with the VPC's owned allocations. This is not the effective routing profile, a Site-global VNI override, or a convergence report. Every field is present; null means no stored profile or retained allocation, respectively.
type VpcRoutingState struct {
	// REST ID of the VPC selected in the request, which may differ from its Site-local Core ID.
	VpcId string `json:"vpcId"`
	// Core VPC version observed with these allocations. Use this exact value when approving release of the observed inactive VNI; it is not a DPU-applied version.
	Version string `json:"version"`
	// Persisted profile name, or null when no named profile is stored. Known Core names are returned as the REST aliases `external`, `internal`, and `privileged-internal`; other names are unchanged. The name can be returned even when its Site definition is unavailable.
	RoutingProfile NullableString `json:"routingProfile"`
	// Persisted active VNI verified against pool ownership. Inspection accepts nonnegative values, including zero and values outside the profile-change range; successful inspection does not imply a profile change is supported.
	ActiveVni uint32 `json:"activeVni"`
	// Allocation owned by this VPC in the other pool, or null when the valid active allocation is its only allocation. Inconsistent ownership is an error, not a null result.
	RetainedAllocation NullableVpcRetainedVniAllocation `json:"retainedAllocation"`
}

type _VpcRoutingState VpcRoutingState

// NewVpcRoutingState instantiates a new VpcRoutingState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcRoutingState(vpcId string, version string, routingProfile NullableString, activeVni uint32, retainedAllocation NullableVpcRetainedVniAllocation) *VpcRoutingState {
	this := VpcRoutingState{}
	this.VpcId = vpcId
	this.Version = version
	this.RoutingProfile = routingProfile
	this.ActiveVni = activeVni
	this.RetainedAllocation = retainedAllocation
	return &this
}

// NewVpcRoutingStateWithDefaults instantiates a new VpcRoutingState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcRoutingStateWithDefaults() *VpcRoutingState {
	this := VpcRoutingState{}
	return &this
}

// GetVpcId returns the VpcId field value
func (o *VpcRoutingState) GetVpcId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value
// and a boolean to check if the value has been set.
func (o *VpcRoutingState) GetVpcIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpcId, true
}

// SetVpcId sets field value
func (o *VpcRoutingState) SetVpcId(v string) {
	o.VpcId = v
}

// GetVersion returns the Version field value
func (o *VpcRoutingState) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *VpcRoutingState) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *VpcRoutingState) SetVersion(v string) {
	o.Version = v
}

// GetRoutingProfile returns the RoutingProfile field value
// If the value is explicit nil, the zero value for string will be returned
func (o *VpcRoutingState) GetRoutingProfile() string {
	if o == nil || o.RoutingProfile.Get() == nil {
		var ret string
		return ret
	}

	return *o.RoutingProfile.Get()
}

// GetRoutingProfileOk returns a tuple with the RoutingProfile field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcRoutingState) GetRoutingProfileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoutingProfile.Get(), o.RoutingProfile.IsSet()
}

// SetRoutingProfile sets field value
func (o *VpcRoutingState) SetRoutingProfile(v string) {
	o.RoutingProfile.Set(&v)
}

// GetActiveVni returns the ActiveVni field value
func (o *VpcRoutingState) GetActiveVni() uint32 {
	if o == nil {
		var ret uint32
		return ret
	}

	return o.ActiveVni
}

// GetActiveVniOk returns a tuple with the ActiveVni field value
// and a boolean to check if the value has been set.
func (o *VpcRoutingState) GetActiveVniOk() (*uint32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveVni, true
}

// SetActiveVni sets field value
func (o *VpcRoutingState) SetActiveVni(v uint32) {
	o.ActiveVni = v
}

// GetRetainedAllocation returns the RetainedAllocation field value
// If the value is explicit nil, the zero value for VpcRetainedVniAllocation will be returned
func (o *VpcRoutingState) GetRetainedAllocation() VpcRetainedVniAllocation {
	if o == nil || o.RetainedAllocation.Get() == nil {
		var ret VpcRetainedVniAllocation
		return ret
	}

	return *o.RetainedAllocation.Get()
}

// GetRetainedAllocationOk returns a tuple with the RetainedAllocation field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcRoutingState) GetRetainedAllocationOk() (*VpcRetainedVniAllocation, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainedAllocation.Get(), o.RetainedAllocation.IsSet()
}

// SetRetainedAllocation sets field value
func (o *VpcRoutingState) SetRetainedAllocation(v VpcRetainedVniAllocation) {
	o.RetainedAllocation.Set(&v)
}

func (o VpcRoutingState) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcRoutingState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vpcId"] = o.VpcId
	toSerialize["version"] = o.Version
	toSerialize["routingProfile"] = o.RoutingProfile.Get()
	toSerialize["activeVni"] = o.ActiveVni
	toSerialize["retainedAllocation"] = o.RetainedAllocation.Get()
	return toSerialize, nil
}

func (o *VpcRoutingState) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vpcId",
		"version",
		"routingProfile",
		"activeVni",
		"retainedAllocation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	nullableRequiredProperties := map[string]struct{}{
		"routingProfile":     {},
		"retainedAllocation": {},
	}
	for _, requiredProperty := range requiredProperties {
		_, nullable := nullableRequiredProperties[requiredProperty]
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVpcRoutingState := _VpcRoutingState{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varVpcRoutingState)

	if err != nil {
		return err
	}

	*o = VpcRoutingState(varVpcRoutingState)

	return err
}

type NullableVpcRoutingState struct {
	value *VpcRoutingState
	isSet bool
}

func (v NullableVpcRoutingState) Get() *VpcRoutingState {
	return v.value
}

func (v *NullableVpcRoutingState) Set(val *VpcRoutingState) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcRoutingState) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcRoutingState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcRoutingState(val *VpcRoutingState) *NullableVpcRoutingState {
	return &NullableVpcRoutingState{value: val, isSet: true}
}

func (v NullableVpcRoutingState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcRoutingState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
