// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VpcRoutingProfileUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcRoutingProfileUpdateRequest{}

// VpcRoutingProfileUpdateRequest Change a VPC's named routing profile with automatic or exact VNI selection. REST reads the Core version internally; the caller does not supply a version or manipulate resource pools.
type VpcRoutingProfileUpdateRequest struct {
	// Required Site-configured destination profile with the opposite internal setting from the current profile. The REST aliases `external`, `internal`, and `privileged-internal` map to Core's `EXTERNAL`, `INTERNAL`, and `PRIVILEGED_INTERNAL` names. Other configured names are passed unchanged; this is not a closed enum.
	RoutingProfile string `json:"routingProfile"`
	// Optional exact destination VNI. Omission or null reuses an allocation retained in the destination pool, otherwise allocates automatically. An exact request must match a retained destination allocation if present; otherwise it must name a free materialized entry in the destination pool, regardless of that entry's automatic-allocation setting. A mismatched, occupied, missing, or already active VNI is rejected without fallback.
	Vni NullableInt32 `json:"vni,omitempty"`
}

type _VpcRoutingProfileUpdateRequest VpcRoutingProfileUpdateRequest

// NewVpcRoutingProfileUpdateRequest instantiates a new VpcRoutingProfileUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcRoutingProfileUpdateRequest(routingProfile string) *VpcRoutingProfileUpdateRequest {
	this := VpcRoutingProfileUpdateRequest{}
	this.RoutingProfile = routingProfile
	return &this
}

// NewVpcRoutingProfileUpdateRequestWithDefaults instantiates a new VpcRoutingProfileUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcRoutingProfileUpdateRequestWithDefaults() *VpcRoutingProfileUpdateRequest {
	this := VpcRoutingProfileUpdateRequest{}
	return &this
}

// GetRoutingProfile returns the RoutingProfile field value
func (o *VpcRoutingProfileUpdateRequest) GetRoutingProfile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoutingProfile
}

// GetRoutingProfileOk returns a tuple with the RoutingProfile field value
// and a boolean to check if the value has been set.
func (o *VpcRoutingProfileUpdateRequest) GetRoutingProfileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoutingProfile, true
}

// SetRoutingProfile sets field value
func (o *VpcRoutingProfileUpdateRequest) SetRoutingProfile(v string) {
	o.RoutingProfile = v
}

// GetVni returns the Vni field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcRoutingProfileUpdateRequest) GetVni() int32 {
	if o == nil || IsNil(o.Vni.Get()) {
		var ret int32
		return ret
	}
	return *o.Vni.Get()
}

// GetVniOk returns a tuple with the Vni field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcRoutingProfileUpdateRequest) GetVniOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vni.Get(), o.Vni.IsSet()
}

// HasVni returns a boolean if a field has been set.
func (o *VpcRoutingProfileUpdateRequest) HasVni() bool {
	if o != nil && o.Vni.IsSet() {
		return true
	}

	return false
}

// SetVni gets a reference to the given NullableInt32 and assigns it to the Vni field.
func (o *VpcRoutingProfileUpdateRequest) SetVni(v int32) {
	o.Vni.Set(&v)
}

// SetVniNil sets the value for Vni to be an explicit nil
func (o *VpcRoutingProfileUpdateRequest) SetVniNil() {
	o.Vni.Set(nil)
}

// UnsetVni ensures that no value is present for Vni, not even an explicit nil
func (o *VpcRoutingProfileUpdateRequest) UnsetVni() {
	o.Vni.Unset()
}

func (o VpcRoutingProfileUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcRoutingProfileUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["routingProfile"] = o.RoutingProfile
	if o.Vni.IsSet() {
		toSerialize["vni"] = o.Vni.Get()
	}
	return toSerialize, nil
}

func (o *VpcRoutingProfileUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"routingProfile",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVpcRoutingProfileUpdateRequest := _VpcRoutingProfileUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varVpcRoutingProfileUpdateRequest)

	if err != nil {
		return err
	}

	*o = VpcRoutingProfileUpdateRequest(varVpcRoutingProfileUpdateRequest)

	return err
}

type NullableVpcRoutingProfileUpdateRequest struct {
	value *VpcRoutingProfileUpdateRequest
	isSet bool
}

func (v NullableVpcRoutingProfileUpdateRequest) Get() *VpcRoutingProfileUpdateRequest {
	return v.value
}

func (v *NullableVpcRoutingProfileUpdateRequest) Set(val *VpcRoutingProfileUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcRoutingProfileUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcRoutingProfileUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcRoutingProfileUpdateRequest(val *VpcRoutingProfileUpdateRequest) *NullableVpcRoutingProfileUpdateRequest {
	return &NullableVpcRoutingProfileUpdateRequest{value: val, isSet: true}
}

func (v NullableVpcRoutingProfileUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcRoutingProfileUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
