// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// DpuExtensionServiceUpdateRequestData - Replacement deployment spec using the create request's format. Omission or null leaves the existing configuration unchanged.
type DpuExtensionServiceUpdateRequestData struct {
	DpuExtensionServiceDpfHelmChartData *DpuExtensionServiceDpfHelmChartData
	String                              *string
}

// DpuExtensionServiceDpfHelmChartDataAsDpuExtensionServiceUpdateRequestData is a convenience function that returns DpuExtensionServiceDpfHelmChartData wrapped in DpuExtensionServiceUpdateRequestData
func DpuExtensionServiceDpfHelmChartDataAsDpuExtensionServiceUpdateRequestData(v *DpuExtensionServiceDpfHelmChartData) DpuExtensionServiceUpdateRequestData {
	return DpuExtensionServiceUpdateRequestData{
		DpuExtensionServiceDpfHelmChartData: v,
	}
}

// stringAsDpuExtensionServiceUpdateRequestData is a convenience function that returns string wrapped in DpuExtensionServiceUpdateRequestData
func StringAsDpuExtensionServiceUpdateRequestData(v *string) DpuExtensionServiceUpdateRequestData {
	return DpuExtensionServiceUpdateRequestData{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *DpuExtensionServiceUpdateRequestData) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into DpuExtensionServiceDpfHelmChartData
	err = newStrictDecoder(data).Decode(&dst.DpuExtensionServiceDpfHelmChartData)
	if err == nil {
		jsonDpuExtensionServiceDpfHelmChartData, _ := json.Marshal(dst.DpuExtensionServiceDpfHelmChartData)
		if string(jsonDpuExtensionServiceDpfHelmChartData) == "{}" { // empty struct
			dst.DpuExtensionServiceDpfHelmChartData = nil
		} else {
			if err = validator.Validate(dst.DpuExtensionServiceDpfHelmChartData); err != nil {
				dst.DpuExtensionServiceDpfHelmChartData = nil
			} else {
				match++
			}
		}
	} else {
		dst.DpuExtensionServiceDpfHelmChartData = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DpuExtensionServiceDpfHelmChartData = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DpuExtensionServiceUpdateRequestData)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(DpuExtensionServiceUpdateRequestData): %v", err)
		}
		return fmt.Errorf("data failed to match schemas in oneOf(DpuExtensionServiceUpdateRequestData)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DpuExtensionServiceUpdateRequestData) MarshalJSON() ([]byte, error) {
	if src.DpuExtensionServiceDpfHelmChartData != nil {
		return json.Marshal(&src.DpuExtensionServiceDpfHelmChartData)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DpuExtensionServiceUpdateRequestData) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.DpuExtensionServiceDpfHelmChartData != nil {
		return obj.DpuExtensionServiceDpfHelmChartData
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DpuExtensionServiceUpdateRequestData) GetActualInstanceValue() interface{} {
	if obj.DpuExtensionServiceDpfHelmChartData != nil {
		return *obj.DpuExtensionServiceDpfHelmChartData
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableDpuExtensionServiceUpdateRequestData struct {
	value *DpuExtensionServiceUpdateRequestData
	isSet bool
}

func (v NullableDpuExtensionServiceUpdateRequestData) Get() *DpuExtensionServiceUpdateRequestData {
	return v.value
}

func (v *NullableDpuExtensionServiceUpdateRequestData) Set(val *DpuExtensionServiceUpdateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceUpdateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceUpdateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceUpdateRequestData(val *DpuExtensionServiceUpdateRequestData) *NullableDpuExtensionServiceUpdateRequestData {
	return &NullableDpuExtensionServiceUpdateRequestData{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceUpdateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceUpdateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
