// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the PeerTenant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerTenant{}

// PeerTenant Summary of a tenant involved in a VPC peering
type PeerTenant struct {
	// ID of the Tenant
	Id *string `json:"id,omitempty"`
	// Name of the org this tenant belongs to
	Org *string `json:"org,omitempty"`
	// Display name of the org the Tenant belongs to
	OrgDisplayName NullableString `json:"orgDisplayName,omitempty"`
}

// NewPeerTenant instantiates a new PeerTenant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerTenant() *PeerTenant {
	this := PeerTenant{}
	return &this
}

// NewPeerTenantWithDefaults instantiates a new PeerTenant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerTenantWithDefaults() *PeerTenant {
	this := PeerTenant{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PeerTenant) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerTenant) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PeerTenant) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PeerTenant) SetId(v string) {
	o.Id = &v
}

// GetOrg returns the Org field value if set, zero value otherwise.
func (o *PeerTenant) GetOrg() string {
	if o == nil || IsNil(o.Org) {
		var ret string
		return ret
	}
	return *o.Org
}

// GetOrgOk returns a tuple with the Org field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerTenant) GetOrgOk() (*string, bool) {
	if o == nil || IsNil(o.Org) {
		return nil, false
	}
	return o.Org, true
}

// HasOrg returns a boolean if a field has been set.
func (o *PeerTenant) HasOrg() bool {
	if o != nil && !IsNil(o.Org) {
		return true
	}

	return false
}

// SetOrg gets a reference to the given string and assigns it to the Org field.
func (o *PeerTenant) SetOrg(v string) {
	o.Org = &v
}

// GetOrgDisplayName returns the OrgDisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PeerTenant) GetOrgDisplayName() string {
	if o == nil || IsNil(o.OrgDisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.OrgDisplayName.Get()
}

// GetOrgDisplayNameOk returns a tuple with the OrgDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PeerTenant) GetOrgDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrgDisplayName.Get(), o.OrgDisplayName.IsSet()
}

// HasOrgDisplayName returns a boolean if a field has been set.
func (o *PeerTenant) HasOrgDisplayName() bool {
	if o != nil && o.OrgDisplayName.IsSet() {
		return true
	}

	return false
}

// SetOrgDisplayName gets a reference to the given NullableString and assigns it to the OrgDisplayName field.
func (o *PeerTenant) SetOrgDisplayName(v string) {
	o.OrgDisplayName.Set(&v)
}

// SetOrgDisplayNameNil sets the value for OrgDisplayName to be an explicit nil
func (o *PeerTenant) SetOrgDisplayNameNil() {
	o.OrgDisplayName.Set(nil)
}

// UnsetOrgDisplayName ensures that no value is present for OrgDisplayName, not even an explicit nil
func (o *PeerTenant) UnsetOrgDisplayName() {
	o.OrgDisplayName.Unset()
}

func (o PeerTenant) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerTenant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Org) {
		toSerialize["org"] = o.Org
	}
	if o.OrgDisplayName.IsSet() {
		toSerialize["orgDisplayName"] = o.OrgDisplayName.Get()
	}
	return toSerialize, nil
}

type NullablePeerTenant struct {
	value *PeerTenant
	isSet bool
}

func (v NullablePeerTenant) Get() *PeerTenant {
	return v.value
}

func (v *NullablePeerTenant) Set(val *PeerTenant) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerTenant) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerTenant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerTenant(val *PeerTenant) *NullablePeerTenant {
	return &NullablePeerTenant{value: val, isSet: true}
}

func (v NullablePeerTenant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerTenant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
