// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TenantIdentityReencryptFailure type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantIdentityReencryptFailure{}

// TenantIdentityReencryptFailure A single per-field re-wrap failure.
type TenantIdentityReencryptFailure struct {
	// Org whose secret failed to re-wrap.
	OrganizationId string `json:"organizationId"`
	// Name of the field that failed to re-wrap.
	Field string `json:"field"`
	// Error describing why the field could not be re-wrapped.
	Error string `json:"error"`
}

type _TenantIdentityReencryptFailure TenantIdentityReencryptFailure

// NewTenantIdentityReencryptFailure instantiates a new TenantIdentityReencryptFailure object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantIdentityReencryptFailure(organizationId string, field string, error_ string) *TenantIdentityReencryptFailure {
	this := TenantIdentityReencryptFailure{}
	this.OrganizationId = organizationId
	this.Field = field
	this.Error = error_
	return &this
}

// NewTenantIdentityReencryptFailureWithDefaults instantiates a new TenantIdentityReencryptFailure object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantIdentityReencryptFailureWithDefaults() *TenantIdentityReencryptFailure {
	this := TenantIdentityReencryptFailure{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value
func (o *TenantIdentityReencryptFailure) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptFailure) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *TenantIdentityReencryptFailure) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetField returns the Field field value
func (o *TenantIdentityReencryptFailure) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptFailure) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *TenantIdentityReencryptFailure) SetField(v string) {
	o.Field = v
}

// GetError returns the Error field value
func (o *TenantIdentityReencryptFailure) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptFailure) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *TenantIdentityReencryptFailure) SetError(v string) {
	o.Error = v
}

func (o TenantIdentityReencryptFailure) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantIdentityReencryptFailure) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["field"] = o.Field
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *TenantIdentityReencryptFailure) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organizationId",
		"field",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantIdentityReencryptFailure := _TenantIdentityReencryptFailure{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varTenantIdentityReencryptFailure)

	if err != nil {
		return err
	}

	*o = TenantIdentityReencryptFailure(varTenantIdentityReencryptFailure)

	return err
}

type NullableTenantIdentityReencryptFailure struct {
	value *TenantIdentityReencryptFailure
	isSet bool
}

func (v NullableTenantIdentityReencryptFailure) Get() *TenantIdentityReencryptFailure {
	return v.value
}

func (v *NullableTenantIdentityReencryptFailure) Set(val *TenantIdentityReencryptFailure) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantIdentityReencryptFailure) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantIdentityReencryptFailure) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantIdentityReencryptFailure(val *TenantIdentityReencryptFailure) *NullableTenantIdentityReencryptFailure {
	return &NullableTenantIdentityReencryptFailure{value: val, isSet: true}
}

func (v NullableTenantIdentityReencryptFailure) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantIdentityReencryptFailure) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
