// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SpectrumXPartition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpectrumXPartition{}

// SpectrumXPartition SpectrumX Partitions are east-west network segments that Instances attach to over SpectrumX interfaces
type SpectrumXPartition struct {
	// Unique UUID v4 identifier for the SpectrumX Partition
	Id string `json:"id"`
	// Name of the SpectrumX Partition
	Name string `json:"name"`
	// Description of the SpectrumX Partition
	Description NullableString `json:"description,omitempty"`
	// ID of the Site the Partition belongs to
	SiteId string `json:"siteId"`
	// Summary of the Site, present when requested through includeRelation
	Site *SiteSummary `json:"site,omitempty"`
	// ID of the Tenant that owns the Partition
	TenantId string `json:"tenantId"`
	// Summary of the Tenant, present when requested through includeRelation
	Tenant *TenantSummary `json:"tenant,omitempty"`
	// VXLAN Network Identifier for the Partition. Allocated by the Site when the create request omits it
	Vni NullableInt32 `json:"vni,omitempty"`
	// String key-value pairs describing Partition labels. Up to 10 key-value pairs can be specified
	Labels map[string]string `json:"labels,omitempty"`
	// Status of the SpectrumX Partition. A Partition becomes Ready once the Site reports it in inventory
	Status string `json:"status"`
	// Status detail records for the SpectrumX Partition over time
	StatusHistory []StatusDetail `json:"statusHistory,omitempty"`
	// ISO datetime string for when the SpectrumX Partition was created
	Created *time.Time `json:"created,omitempty"`
	// ISO datetime string for when the SpectrumX Partition was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

type _SpectrumXPartition SpectrumXPartition

// NewSpectrumXPartition instantiates a new SpectrumXPartition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpectrumXPartition(id string, name string, siteId string, tenantId string, status string) *SpectrumXPartition {
	this := SpectrumXPartition{}
	this.Id = id
	this.Name = name
	this.SiteId = siteId
	this.TenantId = tenantId
	this.Status = status
	return &this
}

// NewSpectrumXPartitionWithDefaults instantiates a new SpectrumXPartition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpectrumXPartitionWithDefaults() *SpectrumXPartition {
	this := SpectrumXPartition{}
	return &this
}

// GetId returns the Id field value
func (o *SpectrumXPartition) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SpectrumXPartition) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SpectrumXPartition) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SpectrumXPartition) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SpectrumXPartition) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SpectrumXPartition) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpectrumXPartition) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpectrumXPartition) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *SpectrumXPartition) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *SpectrumXPartition) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *SpectrumXPartition) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *SpectrumXPartition) UnsetDescription() {
	o.Description.Unset()
}

// GetSiteId returns the SiteId field value
func (o *SpectrumXPartition) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *SpectrumXPartition) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *SpectrumXPartition) SetSiteId(v string) {
	o.SiteId = v
}

// GetSite returns the Site field value if set, zero value otherwise.
func (o *SpectrumXPartition) GetSite() SiteSummary {
	if o == nil || IsNil(o.Site) {
		var ret SiteSummary
		return ret
	}
	return *o.Site
}

// GetSiteOk returns a tuple with the Site field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpectrumXPartition) GetSiteOk() (*SiteSummary, bool) {
	if o == nil || IsNil(o.Site) {
		return nil, false
	}
	return o.Site, true
}

// HasSite returns a boolean if a field has been set.
func (o *SpectrumXPartition) HasSite() bool {
	if o != nil && !IsNil(o.Site) {
		return true
	}

	return false
}

// SetSite gets a reference to the given SiteSummary and assigns it to the Site field.
func (o *SpectrumXPartition) SetSite(v SiteSummary) {
	o.Site = &v
}

// GetTenantId returns the TenantId field value
func (o *SpectrumXPartition) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *SpectrumXPartition) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *SpectrumXPartition) SetTenantId(v string) {
	o.TenantId = v
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *SpectrumXPartition) GetTenant() TenantSummary {
	if o == nil || IsNil(o.Tenant) {
		var ret TenantSummary
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpectrumXPartition) GetTenantOk() (*TenantSummary, bool) {
	if o == nil || IsNil(o.Tenant) {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *SpectrumXPartition) HasTenant() bool {
	if o != nil && !IsNil(o.Tenant) {
		return true
	}

	return false
}

// SetTenant gets a reference to the given TenantSummary and assigns it to the Tenant field.
func (o *SpectrumXPartition) SetTenant(v TenantSummary) {
	o.Tenant = &v
}

// GetVni returns the Vni field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpectrumXPartition) GetVni() int32 {
	if o == nil || IsNil(o.Vni.Get()) {
		var ret int32
		return ret
	}
	return *o.Vni.Get()
}

// GetVniOk returns a tuple with the Vni field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpectrumXPartition) GetVniOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vni.Get(), o.Vni.IsSet()
}

// HasVni returns a boolean if a field has been set.
func (o *SpectrumXPartition) HasVni() bool {
	if o != nil && o.Vni.IsSet() {
		return true
	}

	return false
}

// SetVni gets a reference to the given NullableInt32 and assigns it to the Vni field.
func (o *SpectrumXPartition) SetVni(v int32) {
	o.Vni.Set(&v)
}

// SetVniNil sets the value for Vni to be an explicit nil
func (o *SpectrumXPartition) SetVniNil() {
	o.Vni.Set(nil)
}

// UnsetVni ensures that no value is present for Vni, not even an explicit nil
func (o *SpectrumXPartition) UnsetVni() {
	o.Vni.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *SpectrumXPartition) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpectrumXPartition) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *SpectrumXPartition) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *SpectrumXPartition) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetStatus returns the Status field value
func (o *SpectrumXPartition) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SpectrumXPartition) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SpectrumXPartition) SetStatus(v string) {
	o.Status = v
}

// GetStatusHistory returns the StatusHistory field value if set, zero value otherwise.
func (o *SpectrumXPartition) GetStatusHistory() []StatusDetail {
	if o == nil || IsNil(o.StatusHistory) {
		var ret []StatusDetail
		return ret
	}
	return o.StatusHistory
}

// GetStatusHistoryOk returns a tuple with the StatusHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpectrumXPartition) GetStatusHistoryOk() ([]StatusDetail, bool) {
	if o == nil || IsNil(o.StatusHistory) {
		return nil, false
	}
	return o.StatusHistory, true
}

// HasStatusHistory returns a boolean if a field has been set.
func (o *SpectrumXPartition) HasStatusHistory() bool {
	if o != nil && !IsNil(o.StatusHistory) {
		return true
	}

	return false
}

// SetStatusHistory gets a reference to the given []StatusDetail and assigns it to the StatusHistory field.
func (o *SpectrumXPartition) SetStatusHistory(v []StatusDetail) {
	o.StatusHistory = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *SpectrumXPartition) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpectrumXPartition) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *SpectrumXPartition) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *SpectrumXPartition) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *SpectrumXPartition) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpectrumXPartition) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *SpectrumXPartition) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *SpectrumXPartition) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o SpectrumXPartition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpectrumXPartition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.Site) {
		toSerialize["site"] = o.Site
	}
	toSerialize["tenantId"] = o.TenantId
	if !IsNil(o.Tenant) {
		toSerialize["tenant"] = o.Tenant
	}
	if o.Vni.IsSet() {
		toSerialize["vni"] = o.Vni.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	toSerialize["status"] = o.Status
	if !IsNil(o.StatusHistory) {
		toSerialize["statusHistory"] = o.StatusHistory
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

func (o *SpectrumXPartition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"siteId",
		"tenantId",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpectrumXPartition := _SpectrumXPartition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSpectrumXPartition)

	if err != nil {
		return err
	}

	*o = SpectrumXPartition(varSpectrumXPartition)

	return err
}

type NullableSpectrumXPartition struct {
	value *SpectrumXPartition
	isSet bool
}

func (v NullableSpectrumXPartition) Get() *SpectrumXPartition {
	return v.value
}

func (v *NullableSpectrumXPartition) Set(val *SpectrumXPartition) {
	v.value = val
	v.isSet = true
}

func (v NullableSpectrumXPartition) IsSet() bool {
	return v.isSet
}

func (v *NullableSpectrumXPartition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpectrumXPartition(val *SpectrumXPartition) *NullableSpectrumXPartition {
	return &NullableSpectrumXPartition{value: val, isSet: true}
}

func (v NullableSpectrumXPartition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpectrumXPartition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
