// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VpcInactiveVniReleaseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcInactiveVniReleaseRequest{}

// VpcInactiveVniReleaseRequest Release the exact inactive VNI from the operator's authoritative observation after independently verifying convergence. REST preserves the supplied version and does not look up a replacement.
type VpcInactiveVniReleaseRequest struct {
	// Exact Core VPC version from routing-state inspection used for the release decision, in `V<counter>-T<microseconds>` format. Missing or malformed versions are rejected. A stale version returns 412; after an ambiguous release, that error does not prove whether the previous release committed.
	IfVersionMatch string `json:"ifVersionMatch"`
	// Exact retained VNI observed with `ifVersionMatch`. It must match the VPC's inactive allocation and differ from its active VNI.
	ExpectedInactiveVni int32 `json:"expectedInactiveVni"`
}

type _VpcInactiveVniReleaseRequest VpcInactiveVniReleaseRequest

// NewVpcInactiveVniReleaseRequest instantiates a new VpcInactiveVniReleaseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcInactiveVniReleaseRequest(ifVersionMatch string, expectedInactiveVni int32) *VpcInactiveVniReleaseRequest {
	this := VpcInactiveVniReleaseRequest{}
	this.IfVersionMatch = ifVersionMatch
	this.ExpectedInactiveVni = expectedInactiveVni
	return &this
}

// NewVpcInactiveVniReleaseRequestWithDefaults instantiates a new VpcInactiveVniReleaseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcInactiveVniReleaseRequestWithDefaults() *VpcInactiveVniReleaseRequest {
	this := VpcInactiveVniReleaseRequest{}
	return &this
}

// GetIfVersionMatch returns the IfVersionMatch field value
func (o *VpcInactiveVniReleaseRequest) GetIfVersionMatch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IfVersionMatch
}

// GetIfVersionMatchOk returns a tuple with the IfVersionMatch field value
// and a boolean to check if the value has been set.
func (o *VpcInactiveVniReleaseRequest) GetIfVersionMatchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IfVersionMatch, true
}

// SetIfVersionMatch sets field value
func (o *VpcInactiveVniReleaseRequest) SetIfVersionMatch(v string) {
	o.IfVersionMatch = v
}

// GetExpectedInactiveVni returns the ExpectedInactiveVni field value
func (o *VpcInactiveVniReleaseRequest) GetExpectedInactiveVni() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpectedInactiveVni
}

// GetExpectedInactiveVniOk returns a tuple with the ExpectedInactiveVni field value
// and a boolean to check if the value has been set.
func (o *VpcInactiveVniReleaseRequest) GetExpectedInactiveVniOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedInactiveVni, true
}

// SetExpectedInactiveVni sets field value
func (o *VpcInactiveVniReleaseRequest) SetExpectedInactiveVni(v int32) {
	o.ExpectedInactiveVni = v
}

func (o VpcInactiveVniReleaseRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcInactiveVniReleaseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ifVersionMatch"] = o.IfVersionMatch
	toSerialize["expectedInactiveVni"] = o.ExpectedInactiveVni
	return toSerialize, nil
}

func (o *VpcInactiveVniReleaseRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ifVersionMatch",
		"expectedInactiveVni",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVpcInactiveVniReleaseRequest := _VpcInactiveVniReleaseRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varVpcInactiveVniReleaseRequest)

	if err != nil {
		return err
	}

	*o = VpcInactiveVniReleaseRequest(varVpcInactiveVniReleaseRequest)

	return err
}

type NullableVpcInactiveVniReleaseRequest struct {
	value *VpcInactiveVniReleaseRequest
	isSet bool
}

func (v NullableVpcInactiveVniReleaseRequest) Get() *VpcInactiveVniReleaseRequest {
	return v.value
}

func (v *NullableVpcInactiveVniReleaseRequest) Set(val *VpcInactiveVniReleaseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcInactiveVniReleaseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcInactiveVniReleaseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcInactiveVniReleaseRequest(val *VpcInactiveVniReleaseRequest) *NullableVpcInactiveVniReleaseRequest {
	return &NullableVpcInactiveVniReleaseRequest{value: val, isSet: true}
}

func (v NullableVpcInactiveVniReleaseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcInactiveVniReleaseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
