// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the AuditEntryBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditEntryBody{}

// AuditEntryBody Audited request body. JSON object bodies retain their properties directly after sensitive fields are recursively obfuscated. Valid non-object JSON is stored in `value`. Malformed JSON is represented by `jsonParseFailed: true` without retaining the raw request content.
type AuditEntryBody struct {
	Value interface{} `json:"value,omitempty"`
	// Indicates that parsing the request body as JSON failed and its raw content was not retained.
	JsonParseFailed      *bool `json:"jsonParseFailed,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AuditEntryBody AuditEntryBody

// NewAuditEntryBody instantiates a new AuditEntryBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditEntryBody() *AuditEntryBody {
	this := AuditEntryBody{}
	return &this
}

// NewAuditEntryBodyWithDefaults instantiates a new AuditEntryBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditEntryBodyWithDefaults() *AuditEntryBody {
	this := AuditEntryBody{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuditEntryBody) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditEntryBody) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *AuditEntryBody) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given interface{} and assigns it to the Value field.
func (o *AuditEntryBody) SetValue(v interface{}) {
	o.Value = v
}

// GetJsonParseFailed returns the JsonParseFailed field value if set, zero value otherwise.
func (o *AuditEntryBody) GetJsonParseFailed() bool {
	if o == nil || IsNil(o.JsonParseFailed) {
		var ret bool
		return ret
	}
	return *o.JsonParseFailed
}

// GetJsonParseFailedOk returns a tuple with the JsonParseFailed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuditEntryBody) GetJsonParseFailedOk() (*bool, bool) {
	if o == nil || IsNil(o.JsonParseFailed) {
		return nil, false
	}
	return o.JsonParseFailed, true
}

// HasJsonParseFailed returns a boolean if a field has been set.
func (o *AuditEntryBody) HasJsonParseFailed() bool {
	if o != nil && !IsNil(o.JsonParseFailed) {
		return true
	}

	return false
}

// SetJsonParseFailed gets a reference to the given bool and assigns it to the JsonParseFailed field.
func (o *AuditEntryBody) SetJsonParseFailed(v bool) {
	o.JsonParseFailed = &v
}

func (o AuditEntryBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditEntryBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.JsonParseFailed) {
		toSerialize["jsonParseFailed"] = o.JsonParseFailed
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuditEntryBody) UnmarshalJSON(data []byte) (err error) {
	varAuditEntryBody := _AuditEntryBody{}

	err = json.Unmarshal(data, &varAuditEntryBody)

	if err != nil {
		return err
	}

	*o = AuditEntryBody(varAuditEntryBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "jsonParseFailed")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuditEntryBody struct {
	value *AuditEntryBody
	isSet bool
}

func (v NullableAuditEntryBody) Get() *AuditEntryBody {
	return v.value
}

func (v *NullableAuditEntryBody) Set(val *AuditEntryBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditEntryBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditEntryBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditEntryBody(val *AuditEntryBody) *NullableAuditEntryBody {
	return &NullableAuditEntryBody{value: val, isSet: true}
}

func (v NullableAuditEntryBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditEntryBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
