// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpectrumXPartitionCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpectrumXPartitionCreateRequest{}

// SpectrumXPartitionCreateRequest Request data to create a SpectrumX Partition
type SpectrumXPartitionCreateRequest struct {
	// Name of the Partition to create
	Name string `json:"name"`
	// Optional description of the Partition
	Description NullableString `json:"description,omitempty"`
	// ID of the Site the Partition should belong to
	SiteId string `json:"siteId"`
	// Requested VXLAN Network Identifier. Omit it to let the Site allocate one from its pool. A requested value that is already allocated or outside that pool is rejected by the Site
	Vni NullableInt32 `json:"vni,omitempty"`
	// String key-value pairs describing Partition labels. Up to 10 key-value pairs can be specified
	Labels map[string]string `json:"labels,omitempty"`
}

type _SpectrumXPartitionCreateRequest SpectrumXPartitionCreateRequest

// NewSpectrumXPartitionCreateRequest instantiates a new SpectrumXPartitionCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpectrumXPartitionCreateRequest(name string, siteId string) *SpectrumXPartitionCreateRequest {
	this := SpectrumXPartitionCreateRequest{}
	this.Name = name
	this.SiteId = siteId
	return &this
}

// NewSpectrumXPartitionCreateRequestWithDefaults instantiates a new SpectrumXPartitionCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpectrumXPartitionCreateRequestWithDefaults() *SpectrumXPartitionCreateRequest {
	this := SpectrumXPartitionCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *SpectrumXPartitionCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SpectrumXPartitionCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SpectrumXPartitionCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpectrumXPartitionCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpectrumXPartitionCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *SpectrumXPartitionCreateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *SpectrumXPartitionCreateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *SpectrumXPartitionCreateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *SpectrumXPartitionCreateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetSiteId returns the SiteId field value
func (o *SpectrumXPartitionCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *SpectrumXPartitionCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *SpectrumXPartitionCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetVni returns the Vni field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpectrumXPartitionCreateRequest) GetVni() int32 {
	if o == nil || IsNil(o.Vni.Get()) {
		var ret int32
		return ret
	}
	return *o.Vni.Get()
}

// GetVniOk returns a tuple with the Vni field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpectrumXPartitionCreateRequest) GetVniOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vni.Get(), o.Vni.IsSet()
}

// HasVni returns a boolean if a field has been set.
func (o *SpectrumXPartitionCreateRequest) HasVni() bool {
	if o != nil && o.Vni.IsSet() {
		return true
	}

	return false
}

// SetVni gets a reference to the given NullableInt32 and assigns it to the Vni field.
func (o *SpectrumXPartitionCreateRequest) SetVni(v int32) {
	o.Vni.Set(&v)
}

// SetVniNil sets the value for Vni to be an explicit nil
func (o *SpectrumXPartitionCreateRequest) SetVniNil() {
	o.Vni.Set(nil)
}

// UnsetVni ensures that no value is present for Vni, not even an explicit nil
func (o *SpectrumXPartitionCreateRequest) UnsetVni() {
	o.Vni.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *SpectrumXPartitionCreateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpectrumXPartitionCreateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *SpectrumXPartitionCreateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *SpectrumXPartitionCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o SpectrumXPartitionCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpectrumXPartitionCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["siteId"] = o.SiteId
	if o.Vni.IsSet() {
		toSerialize["vni"] = o.Vni.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *SpectrumXPartitionCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpectrumXPartitionCreateRequest := _SpectrumXPartitionCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSpectrumXPartitionCreateRequest)

	if err != nil {
		return err
	}

	*o = SpectrumXPartitionCreateRequest(varSpectrumXPartitionCreateRequest)

	return err
}

type NullableSpectrumXPartitionCreateRequest struct {
	value *SpectrumXPartitionCreateRequest
	isSet bool
}

func (v NullableSpectrumXPartitionCreateRequest) Get() *SpectrumXPartitionCreateRequest {
	return v.value
}

func (v *NullableSpectrumXPartitionCreateRequest) Set(val *SpectrumXPartitionCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSpectrumXPartitionCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSpectrumXPartitionCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpectrumXPartitionCreateRequest(val *SpectrumXPartitionCreateRequest) *NullableSpectrumXPartitionCreateRequest {
	return &NullableSpectrumXPartitionCreateRequest{value: val, isSet: true}
}

func (v NullableSpectrumXPartitionCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpectrumXPartitionCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
