// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VpcRetainedVniAllocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcRetainedVniAllocation{}

// VpcRetainedVniAllocation VNI still reserved for the VPC in the pool other than its active allocation. Retention alone does not guarantee that a reverse profile change passes current validation.
type VpcRetainedVniAllocation struct {
	// Resource pool containing the retained allocation.
	PoolName string `json:"poolName"`
	// Persisted nonnegative VNI, distinct from the active VNI. Inspection does not establish whether it is valid for a profile change or release.
	Vni uint32 `json:"vni"`
}

type _VpcRetainedVniAllocation VpcRetainedVniAllocation

// NewVpcRetainedVniAllocation instantiates a new VpcRetainedVniAllocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcRetainedVniAllocation(poolName string, vni uint32) *VpcRetainedVniAllocation {
	this := VpcRetainedVniAllocation{}
	this.PoolName = poolName
	this.Vni = vni
	return &this
}

// NewVpcRetainedVniAllocationWithDefaults instantiates a new VpcRetainedVniAllocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcRetainedVniAllocationWithDefaults() *VpcRetainedVniAllocation {
	this := VpcRetainedVniAllocation{}
	return &this
}

// GetPoolName returns the PoolName field value
func (o *VpcRetainedVniAllocation) GetPoolName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolName
}

// GetPoolNameOk returns a tuple with the PoolName field value
// and a boolean to check if the value has been set.
func (o *VpcRetainedVniAllocation) GetPoolNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolName, true
}

// SetPoolName sets field value
func (o *VpcRetainedVniAllocation) SetPoolName(v string) {
	o.PoolName = v
}

// GetVni returns the Vni field value
func (o *VpcRetainedVniAllocation) GetVni() uint32 {
	if o == nil {
		var ret uint32
		return ret
	}

	return o.Vni
}

// GetVniOk returns a tuple with the Vni field value
// and a boolean to check if the value has been set.
func (o *VpcRetainedVniAllocation) GetVniOk() (*uint32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vni, true
}

// SetVni sets field value
func (o *VpcRetainedVniAllocation) SetVni(v uint32) {
	o.Vni = v
}

func (o VpcRetainedVniAllocation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcRetainedVniAllocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["poolName"] = o.PoolName
	toSerialize["vni"] = o.Vni
	return toSerialize, nil
}

func (o *VpcRetainedVniAllocation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"poolName",
		"vni",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVpcRetainedVniAllocation := _VpcRetainedVniAllocation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varVpcRetainedVniAllocation)

	if err != nil {
		return err
	}

	*o = VpcRetainedVniAllocation(varVpcRetainedVniAllocation)

	return err
}

type NullableVpcRetainedVniAllocation struct {
	value *VpcRetainedVniAllocation
	isSet bool
}

func (v NullableVpcRetainedVniAllocation) Get() *VpcRetainedVniAllocation {
	return v.value
}

func (v *NullableVpcRetainedVniAllocation) Set(val *VpcRetainedVniAllocation) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcRetainedVniAllocation) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcRetainedVniAllocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcRetainedVniAllocation(val *VpcRetainedVniAllocation) *NullableVpcRetainedVniAllocation {
	return &NullableVpcRetainedVniAllocation{value: val, isSet: true}
}

func (v NullableVpcRetainedVniAllocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcRetainedVniAllocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
