// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// DpuExtensionServiceDpuTarget DPU placement policy. Primary targets the host's primary attached DPU; AllActive targets DPUs used by instance networking, including legacy fallbacks; All targets every attached DPU.
type DpuExtensionServiceDpuTarget string

// List of DpuExtensionServiceDpuTarget
const (
	DPUEXTENSIONSERVICEDPUTARGET_PRIMARY    DpuExtensionServiceDpuTarget = "Primary"
	DPUEXTENSIONSERVICEDPUTARGET_ALL_ACTIVE DpuExtensionServiceDpuTarget = "AllActive"
	DPUEXTENSIONSERVICEDPUTARGET_ALL        DpuExtensionServiceDpuTarget = "All"
)

// All allowed values of DpuExtensionServiceDpuTarget enum
var AllowedDpuExtensionServiceDpuTargetEnumValues = []DpuExtensionServiceDpuTarget{
	"Primary",
	"AllActive",
	"All",
}

func (v *DpuExtensionServiceDpuTarget) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DpuExtensionServiceDpuTarget(value)
	for _, existing := range AllowedDpuExtensionServiceDpuTargetEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DpuExtensionServiceDpuTarget", value)
}

// NewDpuExtensionServiceDpuTargetFromValue returns a pointer to a valid DpuExtensionServiceDpuTarget
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDpuExtensionServiceDpuTargetFromValue(v string) (*DpuExtensionServiceDpuTarget, error) {
	ev := DpuExtensionServiceDpuTarget(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DpuExtensionServiceDpuTarget: valid values are %v", v, AllowedDpuExtensionServiceDpuTargetEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DpuExtensionServiceDpuTarget) IsValid() bool {
	for _, existing := range AllowedDpuExtensionServiceDpuTargetEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DpuExtensionServiceDpuTarget value
func (v DpuExtensionServiceDpuTarget) Ptr() *DpuExtensionServiceDpuTarget {
	return &v
}

type NullableDpuExtensionServiceDpuTarget struct {
	value *DpuExtensionServiceDpuTarget
	isSet bool
}

func (v NullableDpuExtensionServiceDpuTarget) Get() *DpuExtensionServiceDpuTarget {
	return v.value
}

func (v *NullableDpuExtensionServiceDpuTarget) Set(val *DpuExtensionServiceDpuTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceDpuTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceDpuTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceDpuTarget(val *DpuExtensionServiceDpuTarget) *NullableDpuExtensionServiceDpuTarget {
	return &NullableDpuExtensionServiceDpuTarget{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceDpuTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceDpuTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
