// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// DpuExtensionServiceCreateRequestData - Deployment specification as a string, limited to 131072 UTF-8 bytes. Use a YAML/JSON Pod manifest for KubernetesPod or JSON-encoded Helm configuration for DpfHelmChart. The object schema documents the Helm structure; requests must still send a string.
type DpuExtensionServiceCreateRequestData struct {
	DpuExtensionServiceDpfHelmChartData *DpuExtensionServiceDpfHelmChartData
	String                              *string
}

// DpuExtensionServiceDpfHelmChartDataAsDpuExtensionServiceCreateRequestData is a convenience function that returns DpuExtensionServiceDpfHelmChartData wrapped in DpuExtensionServiceCreateRequestData
func DpuExtensionServiceDpfHelmChartDataAsDpuExtensionServiceCreateRequestData(v *DpuExtensionServiceDpfHelmChartData) DpuExtensionServiceCreateRequestData {
	return DpuExtensionServiceCreateRequestData{
		DpuExtensionServiceDpfHelmChartData: v,
	}
}

// stringAsDpuExtensionServiceCreateRequestData is a convenience function that returns string wrapped in DpuExtensionServiceCreateRequestData
func StringAsDpuExtensionServiceCreateRequestData(v *string) DpuExtensionServiceCreateRequestData {
	return DpuExtensionServiceCreateRequestData{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *DpuExtensionServiceCreateRequestData) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DpuExtensionServiceDpfHelmChartData
	err = newStrictDecoder(data).Decode(&dst.DpuExtensionServiceDpfHelmChartData)
	if err == nil {
		jsonDpuExtensionServiceDpfHelmChartData, _ := json.Marshal(dst.DpuExtensionServiceDpfHelmChartData)
		if string(jsonDpuExtensionServiceDpfHelmChartData) == "{}" { // empty struct
			dst.DpuExtensionServiceDpfHelmChartData = nil
		} else {
			if err = validator.Validate(dst.DpuExtensionServiceDpfHelmChartData); err != nil {
				dst.DpuExtensionServiceDpfHelmChartData = nil
			} else {
				match++
			}
		}
	} else {
		dst.DpuExtensionServiceDpfHelmChartData = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DpuExtensionServiceDpfHelmChartData = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DpuExtensionServiceCreateRequestData)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(DpuExtensionServiceCreateRequestData): %v", err)
		}
		return fmt.Errorf("data failed to match schemas in oneOf(DpuExtensionServiceCreateRequestData)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DpuExtensionServiceCreateRequestData) MarshalJSON() ([]byte, error) {
	if src.DpuExtensionServiceDpfHelmChartData != nil {
		return json.Marshal(&src.DpuExtensionServiceDpfHelmChartData)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DpuExtensionServiceCreateRequestData) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.DpuExtensionServiceDpfHelmChartData != nil {
		return obj.DpuExtensionServiceDpfHelmChartData
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DpuExtensionServiceCreateRequestData) GetActualInstanceValue() interface{} {
	if obj.DpuExtensionServiceDpfHelmChartData != nil {
		return *obj.DpuExtensionServiceDpfHelmChartData
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableDpuExtensionServiceCreateRequestData struct {
	value *DpuExtensionServiceCreateRequestData
	isSet bool
}

func (v NullableDpuExtensionServiceCreateRequestData) Get() *DpuExtensionServiceCreateRequestData {
	return v.value
}

func (v *NullableDpuExtensionServiceCreateRequestData) Set(val *DpuExtensionServiceCreateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceCreateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceCreateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceCreateRequestData(val *DpuExtensionServiceCreateRequestData) *NullableDpuExtensionServiceCreateRequestData {
	return &NullableDpuExtensionServiceCreateRequestData{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceCreateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceCreateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
