/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// OperatingSystemStatus Status values for Operating System objects
type OperatingSystemStatus string

// List of OperatingSystemStatus
const (
	OPERATINGSYSTEMSTATUS_PENDING      OperatingSystemStatus = "Pending"
	OPERATINGSYSTEMSTATUS_PROVISIONING OperatingSystemStatus = "Provisioning"
	OPERATINGSYSTEMSTATUS_SYNCING      OperatingSystemStatus = "Syncing"
	OPERATINGSYSTEMSTATUS_READY        OperatingSystemStatus = "Ready"
	OPERATINGSYSTEMSTATUS_DELETING     OperatingSystemStatus = "Deleting"
	OPERATINGSYSTEMSTATUS_ERROR        OperatingSystemStatus = "Error"
	OPERATINGSYSTEMSTATUS_DEACTIVATED  OperatingSystemStatus = "Deactivated"
)

// All allowed values of OperatingSystemStatus enum
var AllowedOperatingSystemStatusEnumValues = []OperatingSystemStatus{
	"Pending",
	"Provisioning",
	"Syncing",
	"Ready",
	"Deleting",
	"Error",
	"Deactivated",
}

func (v *OperatingSystemStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OperatingSystemStatus(value)
	for _, existing := range AllowedOperatingSystemStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OperatingSystemStatus", value)
}

// NewOperatingSystemStatusFromValue returns a pointer to a valid OperatingSystemStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOperatingSystemStatusFromValue(v string) (*OperatingSystemStatus, error) {
	ev := OperatingSystemStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OperatingSystemStatus: valid values are %v", v, AllowedOperatingSystemStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OperatingSystemStatus) IsValid() bool {
	for _, existing := range AllowedOperatingSystemStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OperatingSystemStatus value
func (v OperatingSystemStatus) Ptr() *OperatingSystemStatus {
	return &v
}

type NullableOperatingSystemStatus struct {
	value *OperatingSystemStatus
	isSet bool
}

func (v NullableOperatingSystemStatus) Get() *OperatingSystemStatus {
	return v.value
}

func (v *NullableOperatingSystemStatus) Set(val *OperatingSystemStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatingSystemStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatingSystemStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatingSystemStatus(val *OperatingSystemStatus) *NullableOperatingSystemStatus {
	return &NullableOperatingSystemStatus{value: val, isSet: true}
}

func (v NullableOperatingSystemStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatingSystemStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
