// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// DpuExtensionServiceDpfHelmChartIntOrString - Integer or string value accepted by DPF
type DpuExtensionServiceDpfHelmChartIntOrString struct {
	Int32  *int32
	String *string
}

// int32AsDpuExtensionServiceDpfHelmChartIntOrString is a convenience function that returns int32 wrapped in DpuExtensionServiceDpfHelmChartIntOrString
func Int32AsDpuExtensionServiceDpfHelmChartIntOrString(v *int32) DpuExtensionServiceDpfHelmChartIntOrString {
	return DpuExtensionServiceDpfHelmChartIntOrString{
		Int32: v,
	}
}

// stringAsDpuExtensionServiceDpfHelmChartIntOrString is a convenience function that returns string wrapped in DpuExtensionServiceDpfHelmChartIntOrString
func StringAsDpuExtensionServiceDpfHelmChartIntOrString(v *string) DpuExtensionServiceDpfHelmChartIntOrString {
	return DpuExtensionServiceDpfHelmChartIntOrString{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *DpuExtensionServiceDpfHelmChartIntOrString) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Int32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DpuExtensionServiceDpfHelmChartIntOrString)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(DpuExtensionServiceDpfHelmChartIntOrString): %v", err)
		}
		return fmt.Errorf("data failed to match schemas in oneOf(DpuExtensionServiceDpfHelmChartIntOrString)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DpuExtensionServiceDpfHelmChartIntOrString) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DpuExtensionServiceDpfHelmChartIntOrString) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Int32 != nil {
		return obj.Int32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DpuExtensionServiceDpfHelmChartIntOrString) GetActualInstanceValue() interface{} {
	if obj.Int32 != nil {
		return *obj.Int32
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableDpuExtensionServiceDpfHelmChartIntOrString struct {
	value *DpuExtensionServiceDpfHelmChartIntOrString
	isSet bool
}

func (v NullableDpuExtensionServiceDpfHelmChartIntOrString) Get() *DpuExtensionServiceDpfHelmChartIntOrString {
	return v.value
}

func (v *NullableDpuExtensionServiceDpfHelmChartIntOrString) Set(val *DpuExtensionServiceDpfHelmChartIntOrString) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceDpfHelmChartIntOrString) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceDpfHelmChartIntOrString) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceDpfHelmChartIntOrString(val *DpuExtensionServiceDpfHelmChartIntOrString) *NullableDpuExtensionServiceDpfHelmChartIntOrString {
	return &NullableDpuExtensionServiceDpfHelmChartIntOrString{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceDpfHelmChartIntOrString) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceDpfHelmChartIntOrString) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
