// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the VpcSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcSummary{}

// VpcSummary Summary of a VPC involved in a VPC peering
type VpcSummary struct {
	// ID of the VPC
	Id *string `json:"id,omitempty"`
	// Name of the VPC
	Name *string `json:"name,omitempty"`
	// Legacy attribute, contains the same value as ID
	ControllerVpcId NullableString `json:"controllerVpcId,omitempty"`
	// Network virtualization type of the VPC
	NetworkVirtualizationType NullableString `json:"networkVirtualizationType,omitempty"`
	// Status of the VPC
	Status *VpcStatus `json:"status,omitempty"`
}

// NewVpcSummary instantiates a new VpcSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcSummary() *VpcSummary {
	this := VpcSummary{}
	return &this
}

// NewVpcSummaryWithDefaults instantiates a new VpcSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcSummaryWithDefaults() *VpcSummary {
	this := VpcSummary{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *VpcSummary) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcSummary) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *VpcSummary) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *VpcSummary) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *VpcSummary) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcSummary) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *VpcSummary) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *VpcSummary) SetName(v string) {
	o.Name = &v
}

// GetControllerVpcId returns the ControllerVpcId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcSummary) GetControllerVpcId() string {
	if o == nil || IsNil(o.ControllerVpcId.Get()) {
		var ret string
		return ret
	}
	return *o.ControllerVpcId.Get()
}

// GetControllerVpcIdOk returns a tuple with the ControllerVpcId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcSummary) GetControllerVpcIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ControllerVpcId.Get(), o.ControllerVpcId.IsSet()
}

// HasControllerVpcId returns a boolean if a field has been set.
func (o *VpcSummary) HasControllerVpcId() bool {
	if o != nil && o.ControllerVpcId.IsSet() {
		return true
	}

	return false
}

// SetControllerVpcId gets a reference to the given NullableString and assigns it to the ControllerVpcId field.
func (o *VpcSummary) SetControllerVpcId(v string) {
	o.ControllerVpcId.Set(&v)
}

// SetControllerVpcIdNil sets the value for ControllerVpcId to be an explicit nil
func (o *VpcSummary) SetControllerVpcIdNil() {
	o.ControllerVpcId.Set(nil)
}

// UnsetControllerVpcId ensures that no value is present for ControllerVpcId, not even an explicit nil
func (o *VpcSummary) UnsetControllerVpcId() {
	o.ControllerVpcId.Unset()
}

// GetNetworkVirtualizationType returns the NetworkVirtualizationType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcSummary) GetNetworkVirtualizationType() string {
	if o == nil || IsNil(o.NetworkVirtualizationType.Get()) {
		var ret string
		return ret
	}
	return *o.NetworkVirtualizationType.Get()
}

// GetNetworkVirtualizationTypeOk returns a tuple with the NetworkVirtualizationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcSummary) GetNetworkVirtualizationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkVirtualizationType.Get(), o.NetworkVirtualizationType.IsSet()
}

// HasNetworkVirtualizationType returns a boolean if a field has been set.
func (o *VpcSummary) HasNetworkVirtualizationType() bool {
	if o != nil && o.NetworkVirtualizationType.IsSet() {
		return true
	}

	return false
}

// SetNetworkVirtualizationType gets a reference to the given NullableString and assigns it to the NetworkVirtualizationType field.
func (o *VpcSummary) SetNetworkVirtualizationType(v string) {
	o.NetworkVirtualizationType.Set(&v)
}

// SetNetworkVirtualizationTypeNil sets the value for NetworkVirtualizationType to be an explicit nil
func (o *VpcSummary) SetNetworkVirtualizationTypeNil() {
	o.NetworkVirtualizationType.Set(nil)
}

// UnsetNetworkVirtualizationType ensures that no value is present for NetworkVirtualizationType, not even an explicit nil
func (o *VpcSummary) UnsetNetworkVirtualizationType() {
	o.NetworkVirtualizationType.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *VpcSummary) GetStatus() VpcStatus {
	if o == nil || IsNil(o.Status) {
		var ret VpcStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcSummary) GetStatusOk() (*VpcStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *VpcSummary) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given VpcStatus and assigns it to the Status field.
func (o *VpcSummary) SetStatus(v VpcStatus) {
	o.Status = &v
}

func (o VpcSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.ControllerVpcId.IsSet() {
		toSerialize["controllerVpcId"] = o.ControllerVpcId.Get()
	}
	if o.NetworkVirtualizationType.IsSet() {
		toSerialize["networkVirtualizationType"] = o.NetworkVirtualizationType.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableVpcSummary struct {
	value *VpcSummary
	isSet bool
}

func (v NullableVpcSummary) Get() *VpcSummary {
	return v.value
}

func (v *NullableVpcSummary) Set(val *VpcSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcSummary(val *VpcSummary) *NullableVpcSummary {
	return &NullableVpcSummary{value: val, isSet: true}
}

func (v NullableVpcSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
