// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// LeakHandlingStatus Flow's leakage-handling status. Unknown means Flow could not determine the status; None means no supported handling task exists; ShuttingDown means a forced-shutdown task is waiting, pending, or running; Down means it completed; and Failed means the latest supported handling task failed or was terminated. Down describes handling progress, not the component's current power state.
type LeakHandlingStatus string

// List of LeakHandlingStatus
const (
	LEAKHANDLINGSTATUS_UNKNOWN       LeakHandlingStatus = "Unknown"
	LEAKHANDLINGSTATUS_NONE          LeakHandlingStatus = "None"
	LEAKHANDLINGSTATUS_SHUTTING_DOWN LeakHandlingStatus = "ShuttingDown"
	LEAKHANDLINGSTATUS_DOWN          LeakHandlingStatus = "Down"
	LEAKHANDLINGSTATUS_FAILED        LeakHandlingStatus = "Failed"
)

// All allowed values of LeakHandlingStatus enum
var AllowedLeakHandlingStatusEnumValues = []LeakHandlingStatus{
	"Unknown",
	"None",
	"ShuttingDown",
	"Down",
	"Failed",
}

func (v *LeakHandlingStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LeakHandlingStatus(value)
	for _, existing := range AllowedLeakHandlingStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LeakHandlingStatus", value)
}

// NewLeakHandlingStatusFromValue returns a pointer to a valid LeakHandlingStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLeakHandlingStatusFromValue(v string) (*LeakHandlingStatus, error) {
	ev := LeakHandlingStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LeakHandlingStatus: valid values are %v", v, AllowedLeakHandlingStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LeakHandlingStatus) IsValid() bool {
	for _, existing := range AllowedLeakHandlingStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LeakHandlingStatus value
func (v LeakHandlingStatus) Ptr() *LeakHandlingStatus {
	return &v
}

type NullableLeakHandlingStatus struct {
	value *LeakHandlingStatus
	isSet bool
}

func (v NullableLeakHandlingStatus) Get() *LeakHandlingStatus {
	return v.value
}

func (v *NullableLeakHandlingStatus) Set(val *LeakHandlingStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableLeakHandlingStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableLeakHandlingStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeakHandlingStatus(val *LeakHandlingStatus) *NullableLeakHandlingStatus {
	return &NullableLeakHandlingStatus{value: val, isSet: true}
}

func (v NullableLeakHandlingStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeakHandlingStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
