// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the DpuExtensionServiceDpfHelmChartServiceDaemonSet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DpuExtensionServiceDpfHelmChartServiceDaemonSet{}

// DpuExtensionServiceDpfHelmChartServiceDaemonSet Optional tenant-configurable DaemonSet settings. NICo owns nodeSelector.
type DpuExtensionServiceDpfHelmChartServiceDaemonSet struct {
	// Optional labels passed to DPF for the service DaemonSet
	Labels map[string]string `json:"labels,omitempty"`
	// Optional annotations passed to DPF for the service DaemonSet
	Annotations map[string]string `json:"annotations,omitempty"`
	// Optional resource quantities, for example {\"nvidia.com/bf_sf\":1,\"memory\":\"500Mi\"}
	Resources      map[string]DpuExtensionServiceDpfHelmChartIntOrString `json:"resources,omitempty"`
	UpdateStrategy NullableDpuExtensionServiceDpfHelmChartUpdateStrategy `json:"updateStrategy,omitempty"`
}

// NewDpuExtensionServiceDpfHelmChartServiceDaemonSet instantiates a new DpuExtensionServiceDpfHelmChartServiceDaemonSet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDpuExtensionServiceDpfHelmChartServiceDaemonSet() *DpuExtensionServiceDpfHelmChartServiceDaemonSet {
	this := DpuExtensionServiceDpfHelmChartServiceDaemonSet{}
	return &this
}

// NewDpuExtensionServiceDpfHelmChartServiceDaemonSetWithDefaults instantiates a new DpuExtensionServiceDpfHelmChartServiceDaemonSet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDpuExtensionServiceDpfHelmChartServiceDaemonSetWithDefaults() *DpuExtensionServiceDpfHelmChartServiceDaemonSet {
	this := DpuExtensionServiceDpfHelmChartServiceDaemonSet{}
	return &this
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) GetAnnotations() map[string]string {
	if o == nil || IsNil(o.Annotations) {
		var ret map[string]string
		return ret
	}
	return o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) GetAnnotationsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return map[string]string{}, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) SetAnnotations(v map[string]string) {
	o.Annotations = v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) GetResources() map[string]DpuExtensionServiceDpfHelmChartIntOrString {
	if o == nil || IsNil(o.Resources) {
		var ret map[string]DpuExtensionServiceDpfHelmChartIntOrString
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) GetResourcesOk() (map[string]DpuExtensionServiceDpfHelmChartIntOrString, bool) {
	if o == nil || IsNil(o.Resources) {
		return map[string]DpuExtensionServiceDpfHelmChartIntOrString{}, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given map[string]DpuExtensionServiceDpfHelmChartIntOrString and assigns it to the Resources field.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) SetResources(v map[string]DpuExtensionServiceDpfHelmChartIntOrString) {
	o.Resources = v
}

// GetUpdateStrategy returns the UpdateStrategy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) GetUpdateStrategy() DpuExtensionServiceDpfHelmChartUpdateStrategy {
	if o == nil || IsNil(o.UpdateStrategy.Get()) {
		var ret DpuExtensionServiceDpfHelmChartUpdateStrategy
		return ret
	}
	return *o.UpdateStrategy.Get()
}

// GetUpdateStrategyOk returns a tuple with the UpdateStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) GetUpdateStrategyOk() (*DpuExtensionServiceDpfHelmChartUpdateStrategy, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdateStrategy.Get(), o.UpdateStrategy.IsSet()
}

// HasUpdateStrategy returns a boolean if a field has been set.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) HasUpdateStrategy() bool {
	if o != nil && o.UpdateStrategy.IsSet() {
		return true
	}

	return false
}

// SetUpdateStrategy gets a reference to the given NullableDpuExtensionServiceDpfHelmChartUpdateStrategy and assigns it to the UpdateStrategy field.
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) SetUpdateStrategy(v DpuExtensionServiceDpfHelmChartUpdateStrategy) {
	o.UpdateStrategy.Set(&v)
}

// SetUpdateStrategyNil sets the value for UpdateStrategy to be an explicit nil
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) SetUpdateStrategyNil() {
	o.UpdateStrategy.Set(nil)
}

// UnsetUpdateStrategy ensures that no value is present for UpdateStrategy, not even an explicit nil
func (o *DpuExtensionServiceDpfHelmChartServiceDaemonSet) UnsetUpdateStrategy() {
	o.UpdateStrategy.Unset()
}

func (o DpuExtensionServiceDpfHelmChartServiceDaemonSet) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DpuExtensionServiceDpfHelmChartServiceDaemonSet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if o.UpdateStrategy.IsSet() {
		toSerialize["updateStrategy"] = o.UpdateStrategy.Get()
	}
	return toSerialize, nil
}

type NullableDpuExtensionServiceDpfHelmChartServiceDaemonSet struct {
	value *DpuExtensionServiceDpfHelmChartServiceDaemonSet
	isSet bool
}

func (v NullableDpuExtensionServiceDpfHelmChartServiceDaemonSet) Get() *DpuExtensionServiceDpfHelmChartServiceDaemonSet {
	return v.value
}

func (v *NullableDpuExtensionServiceDpfHelmChartServiceDaemonSet) Set(val *DpuExtensionServiceDpfHelmChartServiceDaemonSet) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceDpfHelmChartServiceDaemonSet) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceDpfHelmChartServiceDaemonSet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceDpfHelmChartServiceDaemonSet(val *DpuExtensionServiceDpfHelmChartServiceDaemonSet) *NullableDpuExtensionServiceDpfHelmChartServiceDaemonSet {
	return &NullableDpuExtensionServiceDpfHelmChartServiceDaemonSet{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceDpfHelmChartServiceDaemonSet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceDpfHelmChartServiceDaemonSet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
