/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// SshKeyGroupStatus Status values for SSH Key Group objects
type SshKeyGroupStatus string

// List of SshKeyGroupStatus
const (
	SSHKEYGROUPSTATUS_SYNCING  SshKeyGroupStatus = "Syncing"
	SSHKEYGROUPSTATUS_SYNCED   SshKeyGroupStatus = "Synced"
	SSHKEYGROUPSTATUS_ERROR    SshKeyGroupStatus = "Error"
	SSHKEYGROUPSTATUS_DELETING SshKeyGroupStatus = "Deleting"
)

// All allowed values of SshKeyGroupStatus enum
var AllowedSshKeyGroupStatusEnumValues = []SshKeyGroupStatus{
	"Syncing",
	"Synced",
	"Error",
	"Deleting",
}

func (v *SshKeyGroupStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SshKeyGroupStatus(value)
	for _, existing := range AllowedSshKeyGroupStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SshKeyGroupStatus", value)
}

// NewSshKeyGroupStatusFromValue returns a pointer to a valid SshKeyGroupStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSshKeyGroupStatusFromValue(v string) (*SshKeyGroupStatus, error) {
	ev := SshKeyGroupStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SshKeyGroupStatus: valid values are %v", v, AllowedSshKeyGroupStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SshKeyGroupStatus) IsValid() bool {
	for _, existing := range AllowedSshKeyGroupStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SshKeyGroupStatus value
func (v SshKeyGroupStatus) Ptr() *SshKeyGroupStatus {
	return &v
}

type NullableSshKeyGroupStatus struct {
	value *SshKeyGroupStatus
	isSet bool
}

func (v NullableSshKeyGroupStatus) Get() *SshKeyGroupStatus {
	return v.value
}

func (v *NullableSshKeyGroupStatus) Set(val *SshKeyGroupStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSshKeyGroupStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSshKeyGroupStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSshKeyGroupStatus(val *SshKeyGroupStatus) *NullableSshKeyGroupStatus {
	return &NullableSshKeyGroupStatus{value: val, isSet: true}
}

func (v NullableSshKeyGroupStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSshKeyGroupStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
