// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpectrumXPartitionSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpectrumXPartitionSummary{}

// SpectrumXPartitionSummary Summary of a SpectrumX Partition nested under another resource
type SpectrumXPartitionSummary struct {
	// ID of the SpectrumX Partition
	Id string `json:"id"`
	// Name of the SpectrumX Partition
	Name string `json:"name"`
	// ID of the Site the Partition belongs to
	SiteId string `json:"siteId"`
	// VXLAN Network Identifier allocated for the Partition
	Vni NullableInt32 `json:"vni,omitempty"`
	// Status of the SpectrumX Partition
	Status string `json:"status"`
}

type _SpectrumXPartitionSummary SpectrumXPartitionSummary

// NewSpectrumXPartitionSummary instantiates a new SpectrumXPartitionSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpectrumXPartitionSummary(id string, name string, siteId string, status string) *SpectrumXPartitionSummary {
	this := SpectrumXPartitionSummary{}
	this.Id = id
	this.Name = name
	this.SiteId = siteId
	this.Status = status
	return &this
}

// NewSpectrumXPartitionSummaryWithDefaults instantiates a new SpectrumXPartitionSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpectrumXPartitionSummaryWithDefaults() *SpectrumXPartitionSummary {
	this := SpectrumXPartitionSummary{}
	return &this
}

// GetId returns the Id field value
func (o *SpectrumXPartitionSummary) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SpectrumXPartitionSummary) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SpectrumXPartitionSummary) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SpectrumXPartitionSummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SpectrumXPartitionSummary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SpectrumXPartitionSummary) SetName(v string) {
	o.Name = v
}

// GetSiteId returns the SiteId field value
func (o *SpectrumXPartitionSummary) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *SpectrumXPartitionSummary) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *SpectrumXPartitionSummary) SetSiteId(v string) {
	o.SiteId = v
}

// GetVni returns the Vni field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpectrumXPartitionSummary) GetVni() int32 {
	if o == nil || IsNil(o.Vni.Get()) {
		var ret int32
		return ret
	}
	return *o.Vni.Get()
}

// GetVniOk returns a tuple with the Vni field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpectrumXPartitionSummary) GetVniOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vni.Get(), o.Vni.IsSet()
}

// HasVni returns a boolean if a field has been set.
func (o *SpectrumXPartitionSummary) HasVni() bool {
	if o != nil && o.Vni.IsSet() {
		return true
	}

	return false
}

// SetVni gets a reference to the given NullableInt32 and assigns it to the Vni field.
func (o *SpectrumXPartitionSummary) SetVni(v int32) {
	o.Vni.Set(&v)
}

// SetVniNil sets the value for Vni to be an explicit nil
func (o *SpectrumXPartitionSummary) SetVniNil() {
	o.Vni.Set(nil)
}

// UnsetVni ensures that no value is present for Vni, not even an explicit nil
func (o *SpectrumXPartitionSummary) UnsetVni() {
	o.Vni.Unset()
}

// GetStatus returns the Status field value
func (o *SpectrumXPartitionSummary) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SpectrumXPartitionSummary) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SpectrumXPartitionSummary) SetStatus(v string) {
	o.Status = v
}

func (o SpectrumXPartitionSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpectrumXPartitionSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["siteId"] = o.SiteId
	if o.Vni.IsSet() {
		toSerialize["vni"] = o.Vni.Get()
	}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *SpectrumXPartitionSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"siteId",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpectrumXPartitionSummary := _SpectrumXPartitionSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSpectrumXPartitionSummary)

	if err != nil {
		return err
	}

	*o = SpectrumXPartitionSummary(varSpectrumXPartitionSummary)

	return err
}

type NullableSpectrumXPartitionSummary struct {
	value *SpectrumXPartitionSummary
	isSet bool
}

func (v NullableSpectrumXPartitionSummary) Get() *SpectrumXPartitionSummary {
	return v.value
}

func (v *NullableSpectrumXPartitionSummary) Set(val *SpectrumXPartitionSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableSpectrumXPartitionSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableSpectrumXPartitionSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpectrumXPartitionSummary(val *SpectrumXPartitionSummary) *NullableSpectrumXPartitionSummary {
	return &NullableSpectrumXPartitionSummary{value: val, isSet: true}
}

func (v NullableSpectrumXPartitionSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpectrumXPartitionSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
