// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TenantIdentityReencryptSecretsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantIdentityReencryptSecretsResponse{}

// TenantIdentityReencryptSecretsResponse Counters and per-field failures from a reencrypt run.
type TenantIdentityReencryptSecretsResponse struct {
	// Number of rows examined.
	RowsExamined int32 `json:"rowsExamined"`
	// Number of rows re-wrapped with the current key.
	RowsUpdated int32 `json:"rowsUpdated"`
	// Number of rows skipped because all fields were already on the target key.
	RowsSkippedAllOnTarget int32 `json:"rowsSkippedAllOnTarget"`
	// Number of individual fields re-wrapped.
	FieldsReencrypted int32 `json:"fieldsReencrypted"`
	// Number of fields skipped because they were already on the target key.
	FieldsSkippedOnTarget int32 `json:"fieldsSkippedOnTarget"`
	// Number of rows with at least one field that failed to re-wrap.
	RowsFailed int32 `json:"rowsFailed"`
	// Per-field re-wrap failures; an empty array when none occurred.
	Failures []TenantIdentityReencryptFailure `json:"failures"`
	// Site machine_identity.current_encryption_key_id used as the re-wrap target.
	CurrentEncryptionKeyId string `json:"currentEncryptionKeyId"`
}

type _TenantIdentityReencryptSecretsResponse TenantIdentityReencryptSecretsResponse

// NewTenantIdentityReencryptSecretsResponse instantiates a new TenantIdentityReencryptSecretsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantIdentityReencryptSecretsResponse(rowsExamined int32, rowsUpdated int32, rowsSkippedAllOnTarget int32, fieldsReencrypted int32, fieldsSkippedOnTarget int32, rowsFailed int32, failures []TenantIdentityReencryptFailure, currentEncryptionKeyId string) *TenantIdentityReencryptSecretsResponse {
	this := TenantIdentityReencryptSecretsResponse{}
	this.RowsExamined = rowsExamined
	this.RowsUpdated = rowsUpdated
	this.RowsSkippedAllOnTarget = rowsSkippedAllOnTarget
	this.FieldsReencrypted = fieldsReencrypted
	this.FieldsSkippedOnTarget = fieldsSkippedOnTarget
	this.RowsFailed = rowsFailed
	this.Failures = failures
	this.CurrentEncryptionKeyId = currentEncryptionKeyId
	return &this
}

// NewTenantIdentityReencryptSecretsResponseWithDefaults instantiates a new TenantIdentityReencryptSecretsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantIdentityReencryptSecretsResponseWithDefaults() *TenantIdentityReencryptSecretsResponse {
	this := TenantIdentityReencryptSecretsResponse{}
	return &this
}

// GetRowsExamined returns the RowsExamined field value
func (o *TenantIdentityReencryptSecretsResponse) GetRowsExamined() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RowsExamined
}

// GetRowsExaminedOk returns a tuple with the RowsExamined field value
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetRowsExaminedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RowsExamined, true
}

// SetRowsExamined sets field value
func (o *TenantIdentityReencryptSecretsResponse) SetRowsExamined(v int32) {
	o.RowsExamined = v
}

// GetRowsUpdated returns the RowsUpdated field value
func (o *TenantIdentityReencryptSecretsResponse) GetRowsUpdated() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RowsUpdated
}

// GetRowsUpdatedOk returns a tuple with the RowsUpdated field value
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetRowsUpdatedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RowsUpdated, true
}

// SetRowsUpdated sets field value
func (o *TenantIdentityReencryptSecretsResponse) SetRowsUpdated(v int32) {
	o.RowsUpdated = v
}

// GetRowsSkippedAllOnTarget returns the RowsSkippedAllOnTarget field value
func (o *TenantIdentityReencryptSecretsResponse) GetRowsSkippedAllOnTarget() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RowsSkippedAllOnTarget
}

// GetRowsSkippedAllOnTargetOk returns a tuple with the RowsSkippedAllOnTarget field value
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetRowsSkippedAllOnTargetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RowsSkippedAllOnTarget, true
}

// SetRowsSkippedAllOnTarget sets field value
func (o *TenantIdentityReencryptSecretsResponse) SetRowsSkippedAllOnTarget(v int32) {
	o.RowsSkippedAllOnTarget = v
}

// GetFieldsReencrypted returns the FieldsReencrypted field value
func (o *TenantIdentityReencryptSecretsResponse) GetFieldsReencrypted() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FieldsReencrypted
}

// GetFieldsReencryptedOk returns a tuple with the FieldsReencrypted field value
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetFieldsReencryptedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldsReencrypted, true
}

// SetFieldsReencrypted sets field value
func (o *TenantIdentityReencryptSecretsResponse) SetFieldsReencrypted(v int32) {
	o.FieldsReencrypted = v
}

// GetFieldsSkippedOnTarget returns the FieldsSkippedOnTarget field value
func (o *TenantIdentityReencryptSecretsResponse) GetFieldsSkippedOnTarget() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FieldsSkippedOnTarget
}

// GetFieldsSkippedOnTargetOk returns a tuple with the FieldsSkippedOnTarget field value
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetFieldsSkippedOnTargetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldsSkippedOnTarget, true
}

// SetFieldsSkippedOnTarget sets field value
func (o *TenantIdentityReencryptSecretsResponse) SetFieldsSkippedOnTarget(v int32) {
	o.FieldsSkippedOnTarget = v
}

// GetRowsFailed returns the RowsFailed field value
func (o *TenantIdentityReencryptSecretsResponse) GetRowsFailed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RowsFailed
}

// GetRowsFailedOk returns a tuple with the RowsFailed field value
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetRowsFailedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RowsFailed, true
}

// SetRowsFailed sets field value
func (o *TenantIdentityReencryptSecretsResponse) SetRowsFailed(v int32) {
	o.RowsFailed = v
}

// GetFailures returns the Failures field value
func (o *TenantIdentityReencryptSecretsResponse) GetFailures() []TenantIdentityReencryptFailure {
	if o == nil {
		var ret []TenantIdentityReencryptFailure
		return ret
	}

	return o.Failures
}

// GetFailuresOk returns a tuple with the Failures field value
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetFailuresOk() ([]TenantIdentityReencryptFailure, bool) {
	if o == nil {
		return nil, false
	}
	return o.Failures, true
}

// SetFailures sets field value
func (o *TenantIdentityReencryptSecretsResponse) SetFailures(v []TenantIdentityReencryptFailure) {
	o.Failures = v
}

// GetCurrentEncryptionKeyId returns the CurrentEncryptionKeyId field value
func (o *TenantIdentityReencryptSecretsResponse) GetCurrentEncryptionKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrentEncryptionKeyId
}

// GetCurrentEncryptionKeyIdOk returns a tuple with the CurrentEncryptionKeyId field value
// and a boolean to check if the value has been set.
func (o *TenantIdentityReencryptSecretsResponse) GetCurrentEncryptionKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentEncryptionKeyId, true
}

// SetCurrentEncryptionKeyId sets field value
func (o *TenantIdentityReencryptSecretsResponse) SetCurrentEncryptionKeyId(v string) {
	o.CurrentEncryptionKeyId = v
}

func (o TenantIdentityReencryptSecretsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantIdentityReencryptSecretsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rowsExamined"] = o.RowsExamined
	toSerialize["rowsUpdated"] = o.RowsUpdated
	toSerialize["rowsSkippedAllOnTarget"] = o.RowsSkippedAllOnTarget
	toSerialize["fieldsReencrypted"] = o.FieldsReencrypted
	toSerialize["fieldsSkippedOnTarget"] = o.FieldsSkippedOnTarget
	toSerialize["rowsFailed"] = o.RowsFailed
	toSerialize["failures"] = o.Failures
	toSerialize["currentEncryptionKeyId"] = o.CurrentEncryptionKeyId
	return toSerialize, nil
}

func (o *TenantIdentityReencryptSecretsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rowsExamined",
		"rowsUpdated",
		"rowsSkippedAllOnTarget",
		"fieldsReencrypted",
		"fieldsSkippedOnTarget",
		"rowsFailed",
		"failures",
		"currentEncryptionKeyId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantIdentityReencryptSecretsResponse := _TenantIdentityReencryptSecretsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varTenantIdentityReencryptSecretsResponse)

	if err != nil {
		return err
	}

	*o = TenantIdentityReencryptSecretsResponse(varTenantIdentityReencryptSecretsResponse)

	return err
}

type NullableTenantIdentityReencryptSecretsResponse struct {
	value *TenantIdentityReencryptSecretsResponse
	isSet bool
}

func (v NullableTenantIdentityReencryptSecretsResponse) Get() *TenantIdentityReencryptSecretsResponse {
	return v.value
}

func (v *NullableTenantIdentityReencryptSecretsResponse) Set(val *TenantIdentityReencryptSecretsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantIdentityReencryptSecretsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantIdentityReencryptSecretsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantIdentityReencryptSecretsResponse(val *TenantIdentityReencryptSecretsResponse) *NullableTenantIdentityReencryptSecretsResponse {
	return &NullableTenantIdentityReencryptSecretsResponse{value: val, isSet: true}
}

func (v NullableTenantIdentityReencryptSecretsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantIdentityReencryptSecretsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
