/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// NetworkSecurityGroupStatus Status values for Network Security Group objects
type NetworkSecurityGroupStatus string

// List of NetworkSecurityGroupStatus
const (
	NETWORKSECURITYGROUPSTATUS_PENDING      NetworkSecurityGroupStatus = "Pending"
	NETWORKSECURITYGROUPSTATUS_PROVISIONING NetworkSecurityGroupStatus = "Provisioning"
	NETWORKSECURITYGROUPSTATUS_READY        NetworkSecurityGroupStatus = "Ready"
	NETWORKSECURITYGROUPSTATUS_DELETING     NetworkSecurityGroupStatus = "Deleting"
	NETWORKSECURITYGROUPSTATUS_ERROR        NetworkSecurityGroupStatus = "Error"
)

// All allowed values of NetworkSecurityGroupStatus enum
var AllowedNetworkSecurityGroupStatusEnumValues = []NetworkSecurityGroupStatus{
	"Pending",
	"Provisioning",
	"Ready",
	"Deleting",
	"Error",
}

func (v *NetworkSecurityGroupStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NetworkSecurityGroupStatus(value)
	for _, existing := range AllowedNetworkSecurityGroupStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NetworkSecurityGroupStatus", value)
}

// NewNetworkSecurityGroupStatusFromValue returns a pointer to a valid NetworkSecurityGroupStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNetworkSecurityGroupStatusFromValue(v string) (*NetworkSecurityGroupStatus, error) {
	ev := NetworkSecurityGroupStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NetworkSecurityGroupStatus: valid values are %v", v, AllowedNetworkSecurityGroupStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NetworkSecurityGroupStatus) IsValid() bool {
	for _, existing := range AllowedNetworkSecurityGroupStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NetworkSecurityGroupStatus value
func (v NetworkSecurityGroupStatus) Ptr() *NetworkSecurityGroupStatus {
	return &v
}

type NullableNetworkSecurityGroupStatus struct {
	value *NetworkSecurityGroupStatus
	isSet bool
}

func (v NullableNetworkSecurityGroupStatus) Get() *NetworkSecurityGroupStatus {
	return v.value
}

func (v *NullableNetworkSecurityGroupStatus) Set(val *NetworkSecurityGroupStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkSecurityGroupStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkSecurityGroupStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkSecurityGroupStatus(val *NetworkSecurityGroupStatus) *NullableNetworkSecurityGroupStatus {
	return &NullableNetworkSecurityGroupStatus{value: val, isSet: true}
}

func (v NullableNetworkSecurityGroupStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkSecurityGroupStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
