// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the DpuExtensionServiceDpfHelmChartUpdateStrategy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DpuExtensionServiceDpfHelmChartUpdateStrategy{}

// DpuExtensionServiceDpfHelmChartUpdateStrategy Optional update strategy passed to DPF
type DpuExtensionServiceDpfHelmChartUpdateStrategy struct {
	// Update strategy type, typically RollingUpdate or OnDelete
	Type          NullableString                                       `json:"type,omitempty"`
	RollingUpdate NullableDpuExtensionServiceDpfHelmChartRollingUpdate `json:"rollingUpdate,omitempty"`
}

// NewDpuExtensionServiceDpfHelmChartUpdateStrategy instantiates a new DpuExtensionServiceDpfHelmChartUpdateStrategy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDpuExtensionServiceDpfHelmChartUpdateStrategy() *DpuExtensionServiceDpfHelmChartUpdateStrategy {
	this := DpuExtensionServiceDpfHelmChartUpdateStrategy{}
	return &this
}

// NewDpuExtensionServiceDpfHelmChartUpdateStrategyWithDefaults instantiates a new DpuExtensionServiceDpfHelmChartUpdateStrategy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDpuExtensionServiceDpfHelmChartUpdateStrategyWithDefaults() *DpuExtensionServiceDpfHelmChartUpdateStrategy {
	this := DpuExtensionServiceDpfHelmChartUpdateStrategy{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DpuExtensionServiceDpfHelmChartUpdateStrategy) GetType() string {
	if o == nil || IsNil(o.Type.Get()) {
		var ret string
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuExtensionServiceDpfHelmChartUpdateStrategy) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *DpuExtensionServiceDpfHelmChartUpdateStrategy) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableString and assigns it to the Type field.
func (o *DpuExtensionServiceDpfHelmChartUpdateStrategy) SetType(v string) {
	o.Type.Set(&v)
}

// SetTypeNil sets the value for Type to be an explicit nil
func (o *DpuExtensionServiceDpfHelmChartUpdateStrategy) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *DpuExtensionServiceDpfHelmChartUpdateStrategy) UnsetType() {
	o.Type.Unset()
}

// GetRollingUpdate returns the RollingUpdate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DpuExtensionServiceDpfHelmChartUpdateStrategy) GetRollingUpdate() DpuExtensionServiceDpfHelmChartRollingUpdate {
	if o == nil || IsNil(o.RollingUpdate.Get()) {
		var ret DpuExtensionServiceDpfHelmChartRollingUpdate
		return ret
	}
	return *o.RollingUpdate.Get()
}

// GetRollingUpdateOk returns a tuple with the RollingUpdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuExtensionServiceDpfHelmChartUpdateStrategy) GetRollingUpdateOk() (*DpuExtensionServiceDpfHelmChartRollingUpdate, bool) {
	if o == nil {
		return nil, false
	}
	return o.RollingUpdate.Get(), o.RollingUpdate.IsSet()
}

// HasRollingUpdate returns a boolean if a field has been set.
func (o *DpuExtensionServiceDpfHelmChartUpdateStrategy) HasRollingUpdate() bool {
	if o != nil && o.RollingUpdate.IsSet() {
		return true
	}

	return false
}

// SetRollingUpdate gets a reference to the given NullableDpuExtensionServiceDpfHelmChartRollingUpdate and assigns it to the RollingUpdate field.
func (o *DpuExtensionServiceDpfHelmChartUpdateStrategy) SetRollingUpdate(v DpuExtensionServiceDpfHelmChartRollingUpdate) {
	o.RollingUpdate.Set(&v)
}

// SetRollingUpdateNil sets the value for RollingUpdate to be an explicit nil
func (o *DpuExtensionServiceDpfHelmChartUpdateStrategy) SetRollingUpdateNil() {
	o.RollingUpdate.Set(nil)
}

// UnsetRollingUpdate ensures that no value is present for RollingUpdate, not even an explicit nil
func (o *DpuExtensionServiceDpfHelmChartUpdateStrategy) UnsetRollingUpdate() {
	o.RollingUpdate.Unset()
}

func (o DpuExtensionServiceDpfHelmChartUpdateStrategy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DpuExtensionServiceDpfHelmChartUpdateStrategy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if o.RollingUpdate.IsSet() {
		toSerialize["rollingUpdate"] = o.RollingUpdate.Get()
	}
	return toSerialize, nil
}

type NullableDpuExtensionServiceDpfHelmChartUpdateStrategy struct {
	value *DpuExtensionServiceDpfHelmChartUpdateStrategy
	isSet bool
}

func (v NullableDpuExtensionServiceDpfHelmChartUpdateStrategy) Get() *DpuExtensionServiceDpfHelmChartUpdateStrategy {
	return v.value
}

func (v *NullableDpuExtensionServiceDpfHelmChartUpdateStrategy) Set(val *DpuExtensionServiceDpfHelmChartUpdateStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceDpfHelmChartUpdateStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceDpfHelmChartUpdateStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceDpfHelmChartUpdateStrategy(val *DpuExtensionServiceDpfHelmChartUpdateStrategy) *NullableDpuExtensionServiceDpfHelmChartUpdateStrategy {
	return &NullableDpuExtensionServiceDpfHelmChartUpdateStrategy{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceDpfHelmChartUpdateStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceDpfHelmChartUpdateStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
